# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': 'Urlop', 'verbose_name_plural': 'Urlopy'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Rodzaj urlopu', 'verbose_name_plural': 'Rodzaje urlopów'},
        ),
    ]
