# Generated by Django 5.0.6 on 2026-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlop', '0002_alter_leaverequest_options_alter_leavetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-date_from'], 'verbose_name': 'Urlop', 'verbose_name_plural': 'Urlopy'},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='days_count',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
