# Generated by Django 5.0.6 on 2026-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlop', '0003_alter_leaverequest_options_leaverequest_approved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='is_paid',
            new_name='counts_against_limit',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
