# Generated by Django 5.0.6 on 2026-02-28 14:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_routedistancecache'),
        ('urlop', '0004_rename_is_paid_leavetype_counts_against_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_carryover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='pool',
            field=models.CharField(choices=[('vacation', 'Wypoczynkowy'), ('care', 'Opiekuńczy'), ('other', 'Inne / nielimitowane')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('vacation_limit', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('carryover_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('adjustment_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('on_demand_limit', models.DecimalField(decimal_places=2, default=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('carryover_deadline', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'user_id'],
                'unique_together': {('company', 'user', 'year')},
            },
        ),
    ]
