# Generated by Django 6.0.8 on 2026-09-26 10:38

import app.urlop.models
from django.db import migrations, models


def normalize_leave_type_codes(apps, schema_editor):
    LeaveType = apps.get_model("urlop", "LeaveType")
    alias = schema_editor.connection.alias
    seen = set()
    for leave_type in LeaveType.objects.using(alias).order_by("company_id", "pk"):
        base = (leave_type.code or "type").strip().lower()[:50] or "type"
        code = base
        suffix = 1
        while (leave_type.company_id, code) in seen:
            suffix += 1
            code = f"{base[:47]}-{suffix}"
        seen.add((leave_type.company_id, code))
        if leave_type.code != code:
            LeaveType.objects.using(alias).filter(pk=leave_type.pk).update(code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_paneluser_options'),
        ('urlop', '0008_add_cancel_permission'),
    ]

    operations = [
        migrations.RunPython(normalize_leave_type_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_year',
            field=models.PositiveIntegerField(default=app.urlop.models.current_leave_year),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_leave_type_code_per_company'),
        ),
    ]
