# Generated by Django 5.0.6 on 2025-11-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('owner', 'Właściciel'), ('manager', 'Manager'), ('employee', 'Pracownik'), ('client', 'Klient')], help_text="Używane tylko przy 'Rola'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text="Używane tylko przy 'Jedna osoba'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(choices=[('user', 'Jedna osoba'), ('role', 'Rola'), ('all', 'Dla wszystkich')], default='user', max_length=20),
        ),
    ]
