# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0002_remove_task_assignee_task_assigned_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Zadanie', 'verbose_name_plural': 'Zadania'},
        ),
    ]
