# Generated by Django 6.0.3 on 2026-03-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('owner', 'Właściciel'), ('manager', 'Manager'), ('biuro', 'Biuro'), ('employee', 'Pracownik'), ('client', 'Klient')], help_text="Używane tylko przy 'Rola'", max_length=20, null=True),
        ),
    ]
