# Generated by Django 6.0.3 on 2026-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0004_alter_task_assigned_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('owner', 'Właściciel'), ('manager', 'Manager'), ('biuro', 'Biuro'), ('podwykonawca', 'Podwykonawca'), ('employee', 'Pracownik'), ('client', 'Klient')], help_text="Używane tylko przy 'Rola'", max_length=20, null=True),
        ),
    ]
