# Generated by Django 6.0.3 on 2026-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('access_task_list', 'Wyświetlanie listy zadań'), ('access_task_create', 'Dodawanie zadań'), ('access_task_delete', 'Usuwanie zadań'), ('access_task_complete', 'Oznaczanie zadań jako wykonane')], 'verbose_name': 'Zadanie', 'verbose_name_plural': 'Zadania'},
        ),
    ]
