# Generated by Django 6.0.3 on 2026-07-05 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_paneluser_options'),
        ('uzytkownik', '0002_companyrolegroup_is_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na potwierdzenie'), ('confirmed', 'Potwierdzony'), ('cancelled', 'Anulowany'), ('expired', 'Wygasł')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='core.company')),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_ownership_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ownership_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przekazanie właściciela',
                'verbose_name_plural': 'Przekazania właściciela',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company',), name='unique_pending_ownership_transfer_per_company')],
            },
        ),
    ]
