# Generated by Django 6.0.3 on 2026-07-05 09:14

from django.conf import settings
from django.db import migrations, models


def move_existing_pending_transfers(apps, schema_editor):
    OwnershipTransfer = apps.get_model("uzytkownik", "OwnershipTransfer")
    OwnershipTransfer.objects.filter(status="pending").update(
        status="recipient_pending"
    )


def restore_old_pending_status(apps, schema_editor):
    OwnershipTransfer = apps.get_model("uzytkownik", "OwnershipTransfer")
    OwnershipTransfer.objects.filter(status="recipient_pending").update(
        status="pending"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_paneluser_options'),
        ('uzytkownik', '0003_ownershiptransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ownershiptransfer',
            name='unique_pending_ownership_transfer_per_company',
        ),
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='status',
            field=models.CharField(choices=[('owner_pending', 'Oczekuje na obecnego właściciela'), ('recipient_pending', 'Oczekuje na przyszłego właściciela'), ('confirmed', 'Potwierdzony'), ('cancelled', 'Anulowany'), ('expired', 'Wygasł')], default='owner_pending', max_length=20),
        ),
        migrations.RunPython(
            move_existing_pending_transfers,
            restore_old_pending_status,
        ),
        migrations.AddConstraint(
            model_name='ownershiptransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['owner_pending', 'recipient_pending'])), fields=('company',), name='unique_pending_ownership_transfer_per_company'),
        ),
    ]
