# Generated by Codex on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_company_logo"),
        ("uzytkownik", "0004_remove_ownershiptransfer_unique_pending_ownership_transfer_per_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTraining",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180, verbose_name="Nazwa szkolenia")),
                ("organizer", models.CharField(blank=True, max_length=180, verbose_name="Organizator")),
                ("completed_at", models.DateField(verbose_name="Data ukończenia")),
                ("valid_until", models.DateField(blank=True, null=True, verbose_name="Ważne do")),
                ("certificate_number", models.CharField(blank=True, max_length=120, verbose_name="Numer certyfikatu")),
                ("notes", models.TextField(blank=True, verbose_name="Notatki")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="employee_trainings", to="core.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trainings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Szkolenie pracownika",
                "verbose_name_plural": "Szkolenia pracowników",
                "ordering": ["-completed_at", "-created_at"],
            },
        ),
    ]
