# Generated by Codex on 2026-07-15

import app.core.fields
import app.uzytkownik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uzytkownik", "0005_employeetraining"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeetraining",
            name="certificate_image",
            field=app.core.fields.TrackedFileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=app.uzytkownik.models.employee_training_certificate_path,
                verbose_name="Zdjęcie certyfikatu",
            ),
        ),
        migrations.AddField(
            model_name="employeetraining",
            name="certificate_image_size",
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                help_text="Rozmiar zapisany w bajtach.",
                verbose_name="Rozmiar zdjęcia certyfikatu",
            ),
        ),
    ]
