# Generated by Codex on 2026-07-15

import app.core.fields
import app.uzytkownik.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uzytkownik", "0006_employeetraining_certificate_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contract_type", models.CharField(choices=[("employment", "Umowa o pracę"), ("mandate", "Umowa zlecenie"), ("specific_work", "Umowa o dzieło"), ("b2b", "Kontrakt B2B"), ("other", "Inna")], default="employment", max_length=30, verbose_name="Rodzaj umowy")),
                ("date_from", models.DateField(verbose_name="Data od")),
                ("date_to", models.DateField(blank=True, null=True, verbose_name="Data do")),
                ("contract_image", app.core.fields.TrackedFileField(blank=True, max_length=500, null=True, upload_to=app.uzytkownik.models.employee_contract_file_path, verbose_name="Zdjęcie umowy")),
                ("contract_image_size", models.PositiveBigIntegerField(default=0, editable=False, help_text="Rozmiar zapisany w bajtach.", verbose_name="Rozmiar zdjęcia umowy")),
                ("notes", models.TextField(blank=True, verbose_name="Notatki")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="employee_contracts", to="core.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contracts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Umowa pracownika",
                "verbose_name_plural": "Umowy pracowników",
                "ordering": ["-date_from", "-created_at"],
            },
        ),
    ]
