# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kalendarz', '0001_initial'),
        ('serwis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='serwis.serviceorder'),
        ),
    ]
