# Generated by Django 6.0.8 on 2026-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0004_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Bez powtarzania'), ('daily', 'Codziennie (dni robocze)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
