# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_address_options_alter_company_options_and_more'),
        ('magazyn', '0001_initial'),
        ('urzadzenie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='urzadzenie.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urzadzenie.product'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='magazyn.warehouse'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='magazyn.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('warehouse', 'product')},
        ),
    ]
