# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Przedmiot na magazynie', 'verbose_name_plural': 'Przedmioty na magazynie'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Historia magazynu', 'verbose_name_plural': 'Historia magazynu'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Magazyn', 'verbose_name_plural': 'Magazyny'},
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
    ]
