# Generated by Django 6.0.3 on 2026-05-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0003_alter_stockitem_options_alter_stockmovement_options_and_more'),
        ('urzadzenie', '0004_product_barcode_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-id'], 'verbose_name': 'Historia magazynu', 'verbose_name_plural': 'Historia magazynu'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='magazyn.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='magazyn.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='urzadzenie.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('in', 'Przyjęcie'), ('out', 'Wydanie'), ('transfer', 'Przesunięcie'), ('adjustment', 'Korekta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='magazyn.warehouse'),
        ),
    ]
