# Generated by Django 6.0.3 on 2026-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('magazyn', '0004_alter_stockmovement_options_and_more'),
        ('urzadzenie', '0004_product_barcode_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimalny stan'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('company', 'warehouse', 'product')},
        ),
    ]
