# Generated by Django 6.0.3 on 2026-09-21 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0034_companysettings_maintenance_number_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('module', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W trakcie'), ('waiting', 'Oczekuje na informacje'), ('resolved', 'Rozwiązane')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('normal', 'Normalny'), ('high', 'Wysoki'), ('urgent', 'Pilny')], default='normal', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie wsparcia',
                'verbose_name_plural': 'Zgłoszenia wsparcia',
                'ordering': ['-created_at'],
                'permissions': [('access_support_list', 'Wyświetlanie listy zgłoszeń wsparcia technicznego'), ('access_support_create', 'Tworzenie zgłoszeń wsparcia technicznego'), ('access_support_detail', 'Wyświetlanie szczegółów zgłoszenia wsparcia technicznego'), ('access_support_update', 'Edytowanie zgłoszeń wsparcia technicznego'), ('access_support_reply', 'Dodawanie odpowiedzi do zgłoszeń wsparcia technicznego'), ('access_support_status_update', 'Zmienianie statusu zgłoszenia wsparcia technicznego')],
            },
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wsparcie.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
