# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'verbose_name': 'Osoba kontaktowa', 'verbose_name_plural': 'Osoby kontaktowe'},
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='position',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('private', 'Osoba prywatna'), ('company', 'Firma')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
