# Generated by Django 5.0.6 on 2025-12-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0002_alter_client_options_alter_contactperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
