# Generated by Django 5.0.6 on 2026-02-07 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('klient', '0004_client_caretaker_client_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('note', 'Notatka'), ('call', 'Rozmowa'), ('email', 'E-mail'), ('task', 'Zadanie'), ('service', 'Serwis'), ('offer', 'Oferta'), ('invoice', 'Faktura'), ('status', 'Zmiana statusu'), ('file', 'Plik'), ('other', 'Inne')], default='note', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('related_app', models.CharField(blank=True, default='', max_length=50)),
                ('related_model', models.CharField(blank=True, default='', max_length=50)),
                ('related_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='klient.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['company', 'client', 'created_at'], name='klient_clie_company_c70f32_idx'), models.Index(fields=['company', 'type', 'created_at'], name='klient_clie_company_32157a_idx')],
            },
        ),
    ]
