# Generated by Django 5.0.6 on 2026-02-07 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('klient', '0006_clientnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientnote',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='clientnote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['company', 'client', 'is_pinned', 'created_at'], name='klient_clie_company_2cbda6_idx'),
        ),
    ]
