# Generated by Django 5.0.6 on 2026-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0008_clientactivity_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactivity',
            name='type',
            field=models.CharField(choices=[('client', 'Klient'), ('note', 'Notatka'), ('call', 'Rozmowa'), ('email', 'E-mail'), ('task', 'Zadanie'), ('service', 'Serwis'), ('offer', 'Oferta'), ('invoice', 'Faktura'), ('status', 'Zmiana statusu'), ('file', 'Plik'), ('other', 'Inne')], default='note', max_length=20),
        ),
    ]
