# Generated by Django 5.0.6 on 2026-02-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('klient', '0009_alter_clientactivity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_locations', to='core.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='klient.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='klient.contactperson')),
            ],
            options={
                'verbose_name': 'Lokalizacja klienta',
                'verbose_name_plural': 'Lokalizacje klienta',
                'ordering': ['-is_default', 'name', 'id'],
                'indexes': [models.Index(fields=['company', 'client', 'is_active'], name='klient_clie_company_8c228b_idx'), models.Index(fields=['company', 'client', 'is_default'], name='klient_clie_company_6d3060_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company', 'client'), name='uniq_default_location_per_client_company'),
        ),
    ]
