# Generated by Django 5.0.6 on 2026-02-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0010_clientlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientlocation',
            name='phone',
        ),
    ]
