# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_address_options_alter_company_options_and_more'),
        ('klient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('work_description', models.TextField()),
                ('travel_cost_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_cost_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('materials_cost_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes_for_invoice', models.TextField(blank=True)),
                ('is_after_offer', models.BooleanField(default=False)),
                ('signed_by_client', models.BooleanField(default=False)),
                ('signed_by_employee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='klient.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
