# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protokol', '0001_initial'),
        ('serwis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='serwis.serviceorder'),
        ),
    ]
