# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'verbose_name': 'Protokol', 'verbose_name_plural': 'Protokoly'},
        ),
    ]
