# Generated by Django 5.0.6 on 2026-02-12 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0003_alter_protocol_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='date',
        ),
        migrations.AddField(
            model_name='protocol',
            name='client_signature',
            field=models.ImageField(blank=True, null=True, upload_to='protocols/signatures/'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='employee_signature',
            field=models.ImageField(blank=True, null=True, upload_to='protocols/signatures/'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocol',
            name='service_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('obsluga', 'Obsługa'), ('gwarancja', 'Gwarancja'), ('do_fakturownia', 'Do zafakturowania'), ('sent', 'Wysłane i zafakturowane')], default='new', max_length=20),
        ),
    ]
