# Generated by Django 5.0.6 on 2026-02-14 11:46

import app.protokol.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('klient', '0009_alter_clientactivity_type'),
        ('protokol', '0004_remove_protocol_date_protocol_client_signature_and_more'),
        ('serwis', '0006_alter_serviceorder_status_zgrania'),
        ('urzadzenie', '0002_alter_product_options_alter_productcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtokolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to=app.protokol.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProtokolUrzadzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sztuki', models.IntegerField(blank=True, null=True)),
                ('cenarazem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='service_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='is_after_offer',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='labor_cost_net',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='materials_cost_net',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='notes_for_invoice',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='travel_cost_net',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='work_description',
        ),
        migrations.AddField(
            model_name='protocol',
            name='czy_powykonawcza',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='dodatkowe_info_pracownik',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='dodatkowe_materialy',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='dodatkowy_komentarz',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='dojazdy_szt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='ile_vat',
            field=models.CharField(blank=True, choices=[('vat_8', '8'), ('vat_23', '23')], null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='is_praca',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='opis',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='pracownicy_szt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protokol_bez_ceny',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protokol_ceny',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='robocizna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='rodzaj_prac',
            field=models.CharField(choices=[('naprawa', 'Naprawa'), ('rozbudowa', 'Rozbudowa'), ('montaz', 'Montaż'), ('przeglad', 'Przegląd'), ('zgranie', 'Zgranie'), ('praca', 'Praca'), ('dostawa', 'Dostawa')], default='naprawa'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sposob_wysylki',
            field=models.CharField(blank=True, choices=[('mail', 'Mailowo'), ('list', 'Listownie')], null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='wykonane_prace',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='serwis.serviceorder'),
        ),
        migrations.AddConstraint(
            model_name='protocol',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_protocol_number_per_company'),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='protokol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokolimg', to='protokol.protocol'),
        ),
        migrations.AddField(
            model_name='protokolurzadzenia',
            name='protokol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokolurz', to='protokol.protocol'),
        ),
        migrations.AddField(
            model_name='protokolurzadzenia',
            name='urzadzenia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urz', to='urzadzenie.product'),
        ),
    ]
