# Generated by Django 5.0.6 on 2026-02-14 13:39

import app.protokol.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('protokol', '0005_protokolimage_protokolurzadzenia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokolimage',
            name='image',
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.protokol.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='kind',
            field=models.CharField(blank=True, choices=[('image', 'Zdjęcie'), ('file', 'Załącznik')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protokol_media_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProtocolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('system', 'System'), ('note', 'Notatka'), ('status', 'Zmiana statusu'), ('signature', 'Podpis'), ('file', 'Plik'), ('other', 'Inne')], default='system', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protocol_activities', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='protokol.protocol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'protocol', 'created_at'], name='protokol_pr_company_e1e0bc_idx'), models.Index(fields=['company', 'type', 'created_at'], name='protokol_pr_company_467f0a_idx')],
            },
        ),
    ]
