# Generated by Django 5.0.6 on 2026-02-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0006_remove_protokolimage_image_protokolimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='rodzaj_prac',
            field=models.CharField(choices=[('naprawa', 'Naprawa'), ('rozbudowa', 'Rozbudowa'), ('montaz', 'Montaż'), ('przeglad', 'Przegląd'), ('zgranie', 'Zgranie'), ('praca', 'Praca'), ('dostawa', 'Dostawa')], default='naprawa', max_length=20),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('obsluga', 'Obsługa'), ('gwarancja', 'Gwarancja'), ('do_zafakturowania', 'Do zafakturowania'), ('sent', 'Wysłane i zafakturowane')], default='new', max_length=20),
        ),
    ]
