# Generated by Django 5.0.6 on 2026-02-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0007_alter_protocol_rodzaj_prac_alter_protocol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='dodatkowe_info_pracownik',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
