# Generated by Django 5.0.6 on 2026-02-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('protokol', '0008_alter_protocol_dodatkowe_info_pracownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='core.address'),
        ),
    ]
