# Generated by Django 5.0.6 on 2026-02-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('protokol', '0009_protocol_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='klient.clientlocation', verbose_name='Lokalizacja'),
        ),
    ]
