# Generated by Django 5.0.6 on 2026-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0010_protocol_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='protocol',
            name='address_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='protocol',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='protocol',
            name='address_street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
