# Generated by Django 5.0.6 on 2026-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0011_protocol_address_city_protocol_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protocol_description',
            field=models.TextField(blank=True),
        ),
    ]
