# Generated by Django 5.0.6 on 2026-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0012_protocol_protocol_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='address_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='address_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ilość km'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Koszt robocizny'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='net_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Suma netto'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='travel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Koszt dojazdu'),
        ),
    ]
