# Generated by Django 5.0.6 on 2026-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0013_protocol_address_latitude_protocol_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='materials_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
