# Generated by Django 6.0.3 on 2026-05-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca', '0003_workactivity'),
        ('protokol', '0014_protocol_materials_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol', to='praca.workorder'),
        ),
    ]
