# Generated by Django 6.0.3 on 2026-05-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_alter_document_options_alter_documentfolder_options'),
        ('protokol', '0015_protocol_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokolimage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_media', related_query_name='protocol_medium', to='dokument.documentfolder', verbose_name='Folder'),
        ),
    ]
