# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
import app.protokol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0019_alter_protocol_rodzaj_prac'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='client_signature_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar podpisu klienta'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='employee_signature_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar podpisu pracownika'),
        ),
        migrations.AddField(
            model_name='protokolimage',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar pliku'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='client_signature',
            field=app.core.fields.TrackedImageField(blank=True, null=True, upload_to='protocols/signatures/'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='employee_signature',
            field=app.core.fields.TrackedImageField(blank=True, null=True, upload_to='protocols/signatures/'),
        ),
        migrations.AlterField(
            model_name='protokolimage',
            name='file',
            field=app.core.fields.TrackedFileField(blank=True, null=True, upload_to=app.protokol.models.user_directory_path),
        ),
    ]
