# Generated by Django 6.0.3 on 2026-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokol', '0020_protocol_client_signature_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='robocizna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
