# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Pojazd', 'verbose_name_plural': 'Pojazdy'},
        ),
    ]
