# Generated by Django 6.0.3 on 2026-05-17 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('pojazd', '0002_alter_vehicle_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspection_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Przegląd ważny do'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ubezpieczenie ważne do'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/photos/', verbose_name='Zdjęcie auta'),
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('repair', 'Naprawa'), ('service', 'Serwis'), ('damage', 'Szkoda'), ('inspection', 'Przegląd'), ('insurance', 'Ubezpieczenie'), ('other', 'Inne')], default='repair', max_length=20, verbose_name='Typ zdarzenia')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('event_date', models.DateField(verbose_name='Data zdarzenia')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Przebieg przy zdarzeniu')),
                ('cost_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt netto')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/events/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_events', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pojazd.vehicle', verbose_name='Pojazd')),
            ],
            options={
                'verbose_name': 'Zdarzenie pojazdu',
                'verbose_name_plural': 'Zdarzenia pojazdów',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
