# Generated by Django 6.0.3 on 2026-05-19 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('pojazd', '0003_vehicle_inspection_valid_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('deleted', 'Usunięto'), ('event_created', 'Dodano zdarzenie'), ('event_updated', 'Edytowano zdarzenie'), ('event_deleted', 'Usunięto zdarzenie')], max_length=30, verbose_name='Akcja')),
                ('description', models.TextField(blank=True, verbose_name='Opis zmiany')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zmiany')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_change_history', to=settings.AUTH_USER_MODEL, verbose_name='Zmienił')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to='pojazd.vehicleevent', verbose_name='Zdarzenie')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='pojazd.vehicle', verbose_name='Pojazd')),
            ],
            options={
                'verbose_name': 'Historia zmian pojazdu',
                'verbose_name_plural': 'Historia zmian pojazdów',
                'ordering': ['-changed_at'],
            },
        ),
    ]
