# Generated by Django 6.0.3 on 2026-05-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_alter_document_options_alter_documentfolder_options'),
        ('pojazd', '0004_vehiclechangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_photos', related_query_name='vehicle_photo', to='dokument.documentfolder', verbose_name='Folder zdjęcia'),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_event_media', related_query_name='vehicle_event_medium', to='dokument.documentfolder', verbose_name='Folder'),
        ),
    ]
