# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0007_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar zdjęcia'),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='photo_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar zdjęcia'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=app.core.fields.TrackedImageField(blank=True, null=True, upload_to='vehicles/photos/', verbose_name='Zdjęcie auta'),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='photo',
            field=app.core.fields.TrackedImageField(blank=True, null=True, upload_to='vehicles/events/', verbose_name='Zdjęcie'),
        ),
    ]
