from .urlop_request_create_view import LeaveRequestCreateView
from .urlop_type_create_view import LeaveTypeCreateView
from .leave_type_list_view import LeaveTypeListView
from .views_allowance_view import LeaveAllowanceListView, GenerateLeaveAllowancesView
from .list_leave_view import HRLeaveListView, HRLeaveApproveView, HRLeaveRejectView, HRLeaveCancelView
from .leave_pdf_view import HRLeavePDFView
from .leave_type_update_view import LeaveTypeUpdateView
from .leave_type_delete_view import LeaveTypeDeleteView
