# Generated by Django 6.0.3 on 2026-05-10 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('urzadzenie', '0003_alter_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Numer zgłoszenia zewnętrznego')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='Firma / dostawca gwarancji')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('reported', 'Zgłoszone'), ('repaired', 'Naprawione')], db_index=True, default='new', max_length=20, verbose_name='Status')),
                ('fault_description', models.TextField(blank=True, verbose_name='Opis usterki')),
                ('reported_at', models.DateField(blank=True, null=True, verbose_name='Data zgłoszenia do gwaranta')),
                ('repaired_at', models.DateField(blank=True, null=True, verbose_name='Data naprawy')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='klient.client', verbose_name='Klient')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warranty_claims', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='klient.clientlocation', verbose_name='Lokalizacja')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='urzadzenie.product', verbose_name='Urządzenie')),
            ],
            options={
                'verbose_name': 'Zgłoszenie gwarancyjne',
                'verbose_name_plural': 'Zgłoszenia gwarancyjne',
                'ordering': ['-created_at'],
            },
        ),
    ]
