# Generated by Django 6.0.3 on 2026-05-16 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwarancja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='companies/warranty_claims/files/', verbose_name='Plik')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Oryginalna nazwa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gwarancja.warrantyclaim', verbose_name='Zgłoszenie')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dodał')),
            ],
            options={
                'verbose_name': 'Załącznik zgłoszenia gwarancyjnego',
                'verbose_name_plural': 'Załączniki zgłoszeń gwarancyjnych',
            },
        ),
    ]
