# Generated by Django 6.0.3 on 2026-05-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwarancja', '0002_warrantyclaimattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaimActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('status', 'Zmiana statusu'), ('reported', 'Zgłoszono'), ('repaired', 'Naprawiono'), ('file', 'Załącznik'), ('note', 'Notatka'), ('system', 'System')], db_index=True, default='system', max_length=30, verbose_name='Typ')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gwarancja.warrantyclaim', verbose_name='Zgłoszenie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claim_activities', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Historia zgłoszenia gwarancyjnego',
                'verbose_name_plural': 'Historia zgłoszeń gwarancyjnych',
                'ordering': ['-created_at'],
            },
        ),
    ]
