# Generated by Django 6.0.3 on 2026-05-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_alter_document_options_alter_documentfolder_options'),
        ('gwarancja', '0003_warrantyclaimactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaimattachment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_attachments', related_query_name='warranty_attachment', to='dokument.documentfolder', verbose_name='Folder'),
        ),
    ]
