# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwarancja', '0006_alter_warrantyclaim_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaimattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar pliku'),
        ),
        migrations.AlterField(
            model_name='warrantyclaimattachment',
            name='file',
            field=app.core.fields.TrackedFileField(upload_to='companies/warranty_claims/files/', verbose_name='Plik'),
        ),
    ]
