# Generated by Django 6.0.3 on 2026-05-21 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('klient', '0011_remove_clientlocation_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa checklisty')),
                ('contract_type', models.CharField(choices=[('cctv', 'Monitoring CCTV'), ('alarm', 'System alarmowy'), ('electrical', 'Elektryka'), ('hvac', 'Klimatyzacja / HVAC'), ('it', 'IT / Sieci'), ('other', 'Inne')], default='other', max_length=30, verbose_name='Typ obsługi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='core.company')),
            ],
            options={
                'verbose_name': 'Szablon checklisty',
                'verbose_name_plural': 'Szablony checklist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Treść punktu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_required', models.BooleanField(default=False, verbose_name='Wymagane')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='obsluga.checklisttemplate', verbose_name='Szablon')),
            ],
            options={
                'verbose_name': 'Punkt checklisty',
                'verbose_name_plural': 'Punkty checklisty',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa obsługi')),
                ('contract_type', models.CharField(choices=[('cctv', 'Monitoring CCTV'), ('alarm', 'System alarmowy'), ('electrical', 'Elektryka'), ('hvac', 'Klimatyzacja / HVAC'), ('it', 'IT / Sieci'), ('other', 'Inne')], default='other', max_length=30, verbose_name='Typ obsługi')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('paused', 'Wstrzymana'), ('ended', 'Zakończona')], default='active', max_length=30, verbose_name='Status')),
                ('frequency', models.CharField(choices=[('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc'), ('quarterly', 'Co kwartał'), ('half_yearly', 'Co pół roku'), ('yearly', 'Co rok'), ('custom', 'Niestandardowo')], default='monthly', max_length=30, verbose_name='Częstotliwość')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Następny termin')),
                ('description', models.TextField(blank=True, verbose_name='Zakres obsługi')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('monthly_price_net', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena miesięczna netto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_service_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='klient.client', verbose_name='Klient')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contracts', to='klient.clientlocation', verbose_name='Lokalizacja klienta')),
            ],
            options={
                'verbose_name': 'Obsługa',
                'verbose_name_plural': 'Obsługi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContractAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa elementu')),
                ('asset_type', models.CharField(choices=[('recorder', 'Rejestrator'), ('camera', 'Kamera'), ('switch', 'Switch'), ('rack', 'Szafa RACK'), ('ups', 'UPS'), ('electrical_board', 'Rozdzielnia'), ('hvac_unit', 'Klimatyzator'), ('heat_pump', 'Pompa ciepła'), ('sensor', 'Czujnik'), ('other', 'Inne')], default='other', max_length=50, verbose_name='Typ elementu')),
                ('location_description', models.CharField(blank=True, help_text='Np. strych klatka 15, serwerownia, rozdzielnia RG, sala konferencyjna.', max_length=255, verbose_name='Lokalizacja elementu')),
                ('producer', models.CharField(blank=True, max_length=150, verbose_name='Producent')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=150, verbose_name='Numer seryjny')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Numer inwentarzowy')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='obsluga.servicecontract', verbose_name='Obsługa')),
            ],
            options={
                'verbose_name': 'Element obsługi',
                'verbose_name_plural': 'Elementy obsługi',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContractParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa parametru')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Wartość')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Jednostka')),
                ('group', models.CharField(blank=True, help_text='Np. CCTV, Elektryka, Klimatyzacja, Ogólne.', max_length=100, verbose_name='Grupa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='obsluga.servicecontract', verbose_name='Obsługa')),
            ],
            options={
                'verbose_name': 'Parametr obsługi',
                'verbose_name_plural': 'Parametry obsługi',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContractPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('role', models.CharField(help_text='Np. zgrywa nagrania, kontakt techniczny, administrator obiektu.', max_length=150, verbose_name='Rola')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='obsluga.servicecontract', verbose_name='Obsługa')),
            ],
            options={
                'verbose_name': 'Osoba przy obsłudze',
                'verbose_name_plural': 'Osoby przy obsłudze',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Zaplanowana'), ('done', 'Wykonana'), ('cancelled', 'Anulowana')], default='planned', max_length=30, verbose_name='Status')),
                ('planned_at', models.DateField(blank=True, null=True, verbose_name='Planowana data')),
                ('performed_at', models.DateField(blank=True, null=True, verbose_name='Data wykonania')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='obsluga.servicecontract', verbose_name='Obsługa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_visits', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
            ],
            options={
                'verbose_name': 'Wizyta obsługi',
                'verbose_name_plural': 'Wizyty obsługi',
                'ordering': ['-planned_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVisitChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Treść punktu')),
                ('is_done', models.BooleanField(default=False, verbose_name='Wykonane')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Komentarz')),
                ('order', models.PositiveIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='obsluga.servicevisit', verbose_name='Wizyta')),
            ],
            options={
                'verbose_name': 'Punkt wykonanej checklisty',
                'verbose_name_plural': 'Punkty wykonanej checklisty',
                'ordering': ['order', 'id'],
            },
        ),
    ]
