# Generated by Django 6.0.3 on 2026-05-23 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsluga', '0002_servicevisit_performed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Koniec okresu'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Początek okresu'),
        ),
        migrations.AddConstraint(
            model_name='servicevisit',
            constraint=models.UniqueConstraint(fields=('contract', 'period_start', 'period_end'), name='unique_service_visit_period'),
        ),
    ]
