# Generated by Django 6.0.3 on 2026-05-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsluga', '0003_servicevisit_period_end_servicevisit_period_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContractMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='obsluga/media/%Y/%m/', verbose_name='Plik')),
                ('media_type', models.CharField(choices=[('image', 'Zdjęcie'), ('file', 'Plik')], default='file', max_length=20, verbose_name='Typ')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Nazwa')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='obsluga.servicecontract', verbose_name='Obsługa')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_service_contract_media', to=settings.AUTH_USER_MODEL, verbose_name='Dodał')),
            ],
            options={
                'verbose_name': 'Plik obsługi',
                'verbose_name_plural': 'Pliki obsługi',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
