# Generated by Django 6.0.3 on 2026-05-23 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsluga', '0004_servicecontractmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContractActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('asset_added', 'Dodano element'), ('asset_updated', 'Zmieniono element'), ('asset_deleted', 'Usunięto element'), ('parameter_added', 'Dodano parametr'), ('parameter_updated', 'Zmieniono parametr'), ('parameter_deleted', 'Usunięto parametr'), ('media_added', 'Dodano plik'), ('visit_confirmed', 'Zatwierdzono przegląd'), ('note', 'Notatka')], default='note', max_length=50, verbose_name='Typ')),
                ('message', models.CharField(max_length=500, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='obsluga.servicecontract', verbose_name='Obsługa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contract_activities', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Historia obsługi',
                'verbose_name_plural': 'Historia obsług',
                'ordering': ['-created_at'],
            },
        ),
    ]
