# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_address_options_alter_company_options_and_more'),
        ('klient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('normal', 'Normalny'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('planned', 'Zaplanowane'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('cancelled', 'Anulowane')], default='new', max_length=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='klient.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='klient.contactperson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
