# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'Zgłoszenie serwisowe', 'verbose_name_plural': 'Zgłoszenia serwisowe'},
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='status_zgrania',
            field=models.CharField(choices=[('new', 'Nowe'), ('nothind', 'Brak materialu'), ('done', 'Zgrane'), ('in_progress', 'W trakcie zgrywania'), ('send', 'Zgrane i przekazane')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('forgoted', 'Zapomniane'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('zgrania', 'Zgrania'), ('cancelled', 'Anulowane')], default='new', max_length=20),
        ),
    ]
