# Generated by Django 5.0.6 on 2026-02-09 19:31

import app.serwis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0002_alter_serviceorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('forgoted', 'Zapomniane'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('zgrania', 'Zgranie'), ('cancelled', 'Anulowane')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceOrderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.serwis.models.service_media_upload_to)),
                ('kind', models.CharField(choices=[('image', 'Zdjęcie'), ('file', 'Załącznik')], max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='serwis.serviceorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_media_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
