# Generated by Django 5.0.6 on 2026-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0005_serviceactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status_zgrania',
            field=models.CharField(blank=True, choices=[('new', 'Nowe'), ('nothind', 'Brak materialu'), ('done', 'Zgrane'), ('in_progress', 'W trakcie zgrywania'), ('send', 'Zgrane i przekazane')], default='new', max_length=20),
        ),
    ]
