# Generated by Django 5.0.6 on 2026-02-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('serwis', '0006_alter_serviceorder_status_zgrania'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.address'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='klient.clientlocation', verbose_name='Lokalizacja'),
        ),
    ]
