# Generated by Django 5.0.6 on 2026-02-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0007_serviceorder_address_serviceorder_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='address_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='address_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='address_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='address_street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
