# Generated by Django 6.0.3 on 2026-05-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_alter_document_options_alter_documentfolder_options'),
        ('serwis', '0008_serviceorder_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordermedia',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_media', related_query_name='service_medium', to='dokument.documentfolder', verbose_name='Folder'),
        ),
    ]
