# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
import app.serwis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0014_alter_serviceorder_status_zgrania'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordermedia',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar pliku'),
        ),
        migrations.AlterField(
            model_name='serviceordermedia',
            name='file',
            field=app.core.fields.TrackedFileField(upload_to=app.serwis.models.service_media_upload_to),
        ),
    ]
