# Generated by Django 6.0.3 on 2026-09-17 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_company_logo'),
        ('serwis', '0015_serviceordermedia_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'permissions': [('access_serwis_nowe', 'Wyświetlanie listy zgłoszeń serwisowych'), ('access_serwis_add', 'Dodawanie zgłoszeń serwisowych'), ('access_serwis_detail', 'Wyświetlanie szczegółów zgłoszenia serwisowego'), ('access_service_note_add', 'Dodawanie notatek serwisowych'), ('access_service_note_pin', 'Przypinanie i odpinanie notatek serwisowych'), ('access_service_note_delete', 'Usuwanie notatek serwisowych'), ('access_serwis_edit', 'Edytowanie zgłoszeń serwisowych'), ('access_serwis_delete', 'Usuwanie zgłoszeń serwisowych'), ('access_serwis_status_update', 'Zmienianie statusu zgłoszenia serwisowego'), ('access_serwis_schedule_update', 'Zmienianie terminu zgłoszenia serwisowego'), ('access_serwis_assign_workers', 'Przypisywanie pracowników do zgłoszenia serwisowego'), ('access_service_media_delete', 'Usuwanie załączników zgłoszenia serwisowego'), ('access_serwis_priority_update', 'Zmienianie priorytetu zgłoszenia serwisowego'), ('access_serwis_status_zgrania_update', 'Zmienianie statusu obsługi'), ('access_client_locations_api', 'Pobieranie lokalizacji klienta w serwisie'), ('access_service_work_log_add', 'Dodawanie dziennych wpisów pracy do serwisu')], 'verbose_name': 'Zgłoszenie serwisowe', 'verbose_name_plural': 'Zgłoszenia serwisowe'},
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='settlement_method',
            field=models.CharField(choices=[('hourly', 'Godzinowo'), ('per_job', 'Od roboty')], default='per_job', max_length=20, verbose_name='Sposób rozliczenia'),
        ),
        migrations.CreateModel(
            name='ServiceWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(verbose_name='Dzień pracy')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Godziny')),
                ('workers_count', models.PositiveIntegerField(default=1, verbose_name='Liczba osób')),
                ('travel_count', models.PositiveIntegerField(default=0, verbose_name='Dojazdy')),
                ('materials', models.TextField(blank=True, default='', verbose_name='Materiał')),
                ('performed_work', models.TextField(blank=True, default='', verbose_name='Wykonane prace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='serwis.serviceorder')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['work_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'service', 'work_date'], name='serwis_serv_company_6d54a6_idx')],
            },
        ),
    ]
