from .klient.apps import KlientConfig
from .protokol.apps import ProtokolConfig
from .core.apps import CoreConfig
from .dokument.apps import DokumentConfig
from .faktura.apps import FakturaConfig
from .gwarancja.apps import GwarancjaConfig
from .kalendarz.apps import KalendarzConfig
from .magazyn.apps import MagazynConfig
from .oferta_praca.apps import Oferta_PracaConfig
from .pojazd.apps import PojazdConfig
from .rcp.apps import RCPConfig
from .serwis.apps import SerwisConfig
from .urlop.apps import UrlopConfig
from .urzadzenie.apps import UrzadzenieConfig
from .uzytkownik.apps import UzytkownikConfig
from .zadanie.apps import ZadanieConfig
from .praca.apps import PracaConfig
from .sprzet.apps import SprzetConfig
from .obsluga.apps import ObslugaConfig
