# Generated by Django 6.0.3 on 2026-05-20 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nazwa')),
                ('category', models.CharField(choices=[('power_tool', 'Elektronarzędzie'), ('hand_tool', 'Narzędzie ręczne'), ('measurement', 'Pomiarowe'), ('ladder', 'Drabiny / podesty'), ('safety', 'BHP'), ('other', 'Inne')], default='power_tool', max_length=40, verbose_name='Kategoria')),
                ('status', models.CharField(choices=[('available', 'Dostępne'), ('in_use', 'W użyciu'), ('service', 'W serwisie'), ('damaged', 'Uszkodzone'), ('lost', 'Zagubione'), ('retired', 'Wycofane')], default='available', max_length=40, verbose_name='Status')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Producent')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Numer seryjny')),
                ('inventory_number', models.CharField(blank=True, max_length=80, verbose_name='Numer ewidencyjny')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data zakupu')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Gwarancja do')),
                ('purchase_price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena zakupu netto')),
                ('storage_place', models.CharField(blank=True, help_text='Np. magazyn, auto serwisowe, biuro.', max_length=160, verbose_name='Miejsce przechowywania')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Ostatni przegląd')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Następny przegląd')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki wewnętrzne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tools', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_tools', to=settings.AUTH_USER_MODEL, verbose_name='Aktualnie u pracownika')),
            ],
            options={
                'verbose_name': 'Narzędzie',
                'verbose_name_plural': 'Narzędzia',
                'ordering': ['name', 'manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Wydano')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Zwrócono')),
                ('return_condition', models.TextField(blank=True, verbose_name='Stan przy zwrocie')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tool_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Wydał')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sprzet.tool', verbose_name='Narzędzie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Wydanie narzędzia',
                'verbose_name_plural': 'Wydania narzędzi',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['company', 'status'], name='sprzet_tool_company_f75ced_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['company', 'category'], name='sprzet_tool_company_14d3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['serial_number'], name='sprzet_tool_serial__f7de78_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['inventory_number'], name='sprzet_tool_invento_5b4536_idx'),
        ),
    ]
