# Generated by Django 6.0.3 on 2026-05-20 20:28

import app.sprzet.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('sprzet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.sprzet.models.tool_image_upload_path, verbose_name='Zdjęcie narzędzia'),
        ),
        migrations.CreateModel(
            name='ToolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('created', 'Utworzono'), ('assigned', 'Wydano'), ('returned', 'Zwrócono'), ('inspection', 'Przegląd'), ('service', 'Serwis / naprawa'), ('damage', 'Uszkodzenie'), ('lost', 'Zagubienie'), ('note', 'Notatka'), ('photo', 'Zdjęcie'), ('other', 'Inne')], default='note', max_length=30, verbose_name='Typ zdarzenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data zdarzenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tool_events', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sprzet.tool', verbose_name='Sprzęt')),
            ],
            options={
                'verbose_name': 'Zdarzenie sprzętu',
                'verbose_name_plural': 'Zdarzenia sprzętu',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
