# Generated by Django 6.0.3 on 2026-05-21 16:52

import app.sprzet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('sprzet', '0002_tool_image_toolevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolevent',
            name='type',
            field=models.CharField(choices=[('repair', 'Naprawa'), ('service', 'Serwis'), ('damage', 'Szkoda'), ('other', 'Inne')], default='repair', max_length=30, verbose_name='Typ zdarzenia'),
        ),
        migrations.CreateModel(
            name='ToolEventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=app.sprzet.models.tool_event_media_upload_path, verbose_name='Zdjęcie')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Opis zdjęcia')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='sprzet.toolevent', verbose_name='Zdarzenie')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tool_event_media', to=settings.AUTH_USER_MODEL, verbose_name='Dodał')),
            ],
            options={
                'verbose_name': 'Zdjęcie zdarzenia sprzętu',
                'verbose_name_plural': 'Zdjęcia zdarzeń sprzętu',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
