# Generated by Django 6.0.3 on 2026-05-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_alter_document_options_alter_documentfolder_options'),
        ('sprzet', '0004_toolhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_images', related_query_name='tool_image', to='dokument.documentfolder', verbose_name='Folder zdjęcia'),
        ),
        migrations.AddField(
            model_name='tooleventmedia',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_event_media', related_query_name='tool_event_medium', to='dokument.documentfolder', verbose_name='Folder'),
        ),
    ]
