# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
import app.sprzet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprzet', '0007_alter_tool_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar zdjęcia'),
        ),
        migrations.AddField(
            model_name='tooleventmedia',
            name='image_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar zdjęcia'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=app.core.fields.TrackedImageField(blank=True, null=True, upload_to=app.sprzet.models.tool_image_upload_path, verbose_name='Zdjęcie narzędzia'),
        ),
        migrations.AlterField(
            model_name='tooleventmedia',
            name='image',
            field=app.core.fields.TrackedImageField(upload_to=app.sprzet.models.tool_event_media_upload_path, verbose_name='Zdjęcie'),
        ),
    ]
