# Generated by Django 6.0.8 on 2026-09-28 21:03

import app.dostawcy.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_companysettings_employee_work_hours'),
        ('urzadzenie', '0008_product_image_size_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('integration_type', models.CharField(choices=[('feed', 'Feed XML/CSV')], default='feed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('feed_url', app.dostawcy.fields.EncryptedTextField()),
                ('feed_type', models.CharField(choices=[('xml', 'XML'), ('csv', 'CSV')], default='xml', max_length=8)),
                ('is_active', models.BooleanField(default=False)),
                ('sync_catalog', models.BooleanField(default=True)),
                ('sync_prices', models.BooleanField(default=True)),
                ('sync_stock', models.BooleanField(default=True)),
                ('default_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Nie uruchomiono'), ('queued', 'Oczekuje'), ('running', 'W trakcie'), ('success', 'Zakończono'), ('partial', 'Zakończono z błędami'), ('error', 'Błąd')], default='never', max_length=12)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync_processed', models.PositiveIntegerField(default=0)),
                ('last_sync_added', models.PositiveIntegerField(default=0)),
                ('last_sync_updated', models.PositiveIntegerField(default=0)),
                ('last_sync_errors', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='dostawcy.supplier')),
            ],
            options={
                'ordering': ['supplier__name'],
                'permissions': [('access_supplier_integrations', 'Wyświetlanie integracji z hurtowniami'), ('access_supplier_integration_save', 'Konfigurowanie integracji z hurtowniami'), ('access_supplier_integration_sync', 'Uruchamianie synchronizacji hurtowni'), ('access_supplier_catalog', 'Wyszukiwanie katalogu produktów dostawców'), ('access_supplier_product_add', 'Dodawanie produktów dostawców do katalogu firmy')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('manufacturer', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dostawcy.supplier')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_price_net', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('local_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_links', to='urzadzenie.product')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='dostawcy.supplierintegration')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_records', to='dostawcy.supplierproduct')),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplierintegration',
            constraint=models.UniqueConstraint(fields=('company', 'supplier'), name='supplier_integration_company_unique'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'sku'], name='supp_prod_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'ean'], name='supp_prod_ean_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'manufacturer'], name='supp_prod_mfr_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'external_id'), name='supplier_product_external_unique'),
        ),
        migrations.AddIndex(
            model_name='suppliercompanyproduct',
            index=models.Index(fields=['company', 'supplier_product'], name='supp_comp_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercompanyproduct',
            index=models.Index(fields=['company', 'last_sync_at'], name='supp_comp_sync_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercompanyproduct',
            constraint=models.UniqueConstraint(fields=('integration', 'supplier_product'), name='supplier_company_product_unique'),
        ),
    ]
