# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Rejestracja czasu pracy', 'verbose_name_plural': 'Rejestracja czasu pracy'},
        ),
    ]
