# Generated by Django 5.0.6 on 2026-03-14 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paneluser_employment_fraction_and_more'),
        ('rcp', '0002_alter_timeentry_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Rejestracja czasu pracy', 'verbose_name_plural': 'Rejestracja czasu pracy'},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='requires_explanation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Roboczy'), ('submitted', 'Wysłany'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='work_mode',
            field=models.CharField(choices=[('office', 'Stacjonarna'), ('remote', 'Zdalna'), ('field', 'Teren')], default='office', max_length=20, verbose_name='Tryb pracy'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Przerwa (min)'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis pracy'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.TimeField(verbose_name='Godzina do'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.TimeField(verbose_name='Godzina od'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['company', 'user', 'date'], name='rcp_timeent_company_8e04fa_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['company', 'status', 'date'], name='rcp_timeent_company_c4463d_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'date'), name='unique_time_entry_per_user_per_day'),
        ),
    ]
