# Generated by Django 6.0.3 on 2026-03-25 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('rcp', '0003_alter_timeentry_options_timeentry_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='work_mode',
            field=models.CharField(choices=[('office', 'Stacjonarna'), ('remote', 'Zdalna'), ('field', 'Teren'), ('delegacja', 'Delegacja')], default='office', max_length=20, verbose_name='Tryb pracy'),
        ),
        migrations.CreateModel(
            name='TimeEntryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('missing', 'Uzupełnienie brakujących godzin'), ('edit', 'Edycja godzin')], max_length=20, verbose_name='Typ wniosku')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Nowa godzina od')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Nowa godzina do')),
                ('reason', models.TextField(verbose_name='Powód')),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Data decyzji')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Powód odrzucenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_time_entry_requests', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rcp.timeentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wniosek RCP',
                'verbose_name_plural': 'Wnioski RCP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='rcp_timeent_company_99f311_idx'), models.Index(fields=['company', 'user'], name='rcp_timeent_company_25db4d_idx'), models.Index(fields=['company', 'request_type'], name='rcp_timeent_company_d67d5b_idx')],
            },
        ),
    ]
