# Generated by Django 6.0.3 on 2026-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0006_alter_timeentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Roboczy'), ('submitted', 'Wysłany'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], db_index=True, default='approved', max_length=20, verbose_name='Status'),
        ),
    ]
