from django.urls import path

from app.uzytkownik.views import (
    EmployeeCreateView,
    EmployeeDeleteView,
    EmployeeStatusToggleView,
    EmployeeListView,
    EmployeeOwnershipTransferConfirmView,
    EmployeeOwnershipTransferView,
    EmployeePermissionListView,
    EmployeePermissionUpdateView,
    CompanyRoleGroupCreateView,
    CompanyRoleGroupDeleteView,
    CompanyRoleGroupUpdateView,
    EmployeeSetPasswordView,
    EmployeeUpdateView,
    UserActivateView,
    UserForgotPasswordView,
    UserLoginView,
    UserLogoutView,
    UserProfileView,
    UserRegisterView,
    UserResetPasswordView,
    UserSetPasswordView,
)

urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('register', UserRegisterView.as_view(), name='register'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('forgot', UserForgotPasswordView.as_view(), name='forgot'),
    path('setpassword/<uidb64>/<token>/', UserSetPasswordView.as_view(), name='setpassword'),
    path('resetpassword/<uidb64>/<token>/', UserResetPasswordView.as_view(), name='resetpassword'),
    path('profile', UserProfileView.as_view(), name='profile'),
    path("aktywacja/<uidb64>/<token>/", UserActivateView.as_view(), name="user_activate"),
    path("pracownicy/dodaj/", EmployeeCreateView.as_view(), name="employee_add"),
    path("pracownicy/<int:pk>/edytuj/", EmployeeUpdateView.as_view(), name="employee_edit"),
    path("pracownicy/<int:pk>/usun/", EmployeeDeleteView.as_view(), name="employee_delete"),
    path("pracownicy/<int:pk>/status/", EmployeeStatusToggleView.as_view(), name="employee_status_toggle"),
    path("pracownicy/<int:pk>/przekaz-wlasciciela/", EmployeeOwnershipTransferView.as_view(), name="employee_ownership_transfer"),
    path("pracownicy/przekazanie/<uuid:transfer_id>/<str:token>/", EmployeeOwnershipTransferConfirmView.as_view(), name="employee_ownership_transfer_confirm"),
    path("pracownicy/lista/", EmployeeListView.as_view(), name="employee_list"),
    path("pracownicy/uprawnienia/", EmployeePermissionListView.as_view(), name="employee_permission_list"),
    path("pracownicy/<int:pk>/uprawnienia/", EmployeePermissionUpdateView.as_view(), name="employee_permission_edit"),
    path("pracownicy/grupy/dodaj/", CompanyRoleGroupCreateView.as_view(), name="employee_group_create"),
    path("pracownicy/grupy/<int:pk>/edytuj/", CompanyRoleGroupUpdateView.as_view(), name="employee_group_edit"),
    path("pracownicy/grupy/<int:pk>/usun/", CompanyRoleGroupDeleteView.as_view(), name="employee_group_delete"),
    path("pracownicy/aktywacja/<uidb64>/<token>/", EmployeeSetPasswordView.as_view(), name="employee_set_password"),
]
