from .vehicle_create_view import VehicleCreateView
from .vehicle_list_view import VehicleListView
from .vehicle_detail_view import VehicleDetailView
from .vehicle_event_create_view import VehicleEventCreateView
from .vehicle_update_view import VehicleUpdateView
from .vehicle_delete_view import VehicleDeleteView
from .vehicle_event_update_view import VehicleEventUpdateView
from .vehicle_event_delete_view import VehicleEventDeleteView