# Generated by Django 5.0.6 on 2025-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('sale_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(default='przelew', max_length=50)),
                ('vat_mode', models.CharField(choices=[('standard', 'Standardowy VAT'), ('exempt', 'Zwolnienie z VAT')], default='standard', max_length=20)),
                ('sending_method', models.CharField(choices=[('email', 'E-mail'), ('post', 'Poczta'), ('portal', 'Portal klienta')], default='email', max_length=20)),
                ('is_final_invoice', models.BooleanField(default=True)),
                ('attach_protocol', models.BooleanField(default=True)),
                ('ksef_number', models.CharField(blank=True, max_length=255)),
                ('ksef_status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('pkwiu', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='szt.', max_length=20)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=23, max_digits=4)),
                ('is_vat_exempt', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VatExemptionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
