# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faktura', '0002_initial'),
        ('oferta_praca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='oferta_praca.offer'),
        ),
    ]
