# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faktura', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Przedmiot faktury', 'verbose_name_plural': 'Przedmioty faktur'},
        ),
    ]
