"""
Django settings for BusinessManager project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Existing process variables (including systemd EnvironmentFile) take precedence.
environ.Env.read_env(BASE_DIR / '.env', overwrite=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

if not DEBUG and (SECRET_KEY == "dev-only-change-me" or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured("Set a strong DJANGO_SECRET_KEY for production.")

# Domena publiczna i domena panelu są konfigurowalne przez środowisko.
# Domyślne wartości pozwalają nadal uruchamiać projekt lokalnie.
PUBLIC_DOMAIN = os.getenv("PUBLIC_DOMAIN", "dapexa.com").strip()
PANEL_DOMAIN = os.getenv("PANEL_DOMAIN", "panel.dapexa.com").strip()

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        f"{PUBLIC_DOMAIN},{PANEL_DOMAIN},localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        f"https://{PUBLIC_DOMAIN},https://{PANEL_DOMAIN},http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if origin.strip()
]

# W produkcji aplikacja działa za HTTPS na reverse proxy (np. Nginx).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "False").lower() in {"1", "true", "yes", "on"}
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "False").lower() in {"1", "true", "yes", "on"}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    
    'app.klient',
    'app.protokol',
    'app.core',
    'app.dokument',
    'app.dostawcy',
    'app.faktura',
    'app.gwarancja',
    'app.kalendarz',
    'app.magazyn',
    'app.oferta_praca',
    'app.pojazd',
    'app.praca',
    'app.rcp',
    'app.serwis',
    'app.urlop',
    'app.urzadzenie',
    'app.uzytkownik',
    'app.zadanie',
    'app.sprzet',
    'app.obsluga',
    'app.wsparcie',
    # allauth
    'allauth',
    'allauth.account',
    "django.contrib.sites",
    'allauth.socialaccount',

    # providers
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    "app.core.middleware.SubscriptionRequiredMiddleware",
    "app.core.middleware.PackageLimitsMiddleware",
    'app.core.middleware.ViewPermissionMiddleware',
    "app.core.middleware.UserTimezoneMiddleware",
]

ROOT_URLCONF = 'BusinessManager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.request",
                "app.core.context_processors.profile_completion",  # << TU
                "app.core.context_processors.current_subscription",
            ],
        },
    },
]

WSGI_APPLICATION = 'BusinessManager.wsgi.application'

AUTH_USER_MODEL = "core.PanelUser"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'business_manager'),
        'USER': os.getenv('DB_USER', 'business_manager'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "app.core.validators.CustomMinimumLengthValidator",
        "OPTIONS": {"min_length": 10},  # możesz zmienić np. na 12
    },
    {
        "NAME": "app.core.validators.UppercaseValidator",
    },
    {
        "NAME": "app.core.validators.DigitValidator",
    },
    {
        "NAME": "app.core.validators.NoRepeatedCharsValidator",
        "OPTIONS": {"max_repeats": 3},  # max 3 takie same znaki pod rząd
    },
    {
        "NAME": "app.core.validators.UserAttributeProhibitionValidator",
        "OPTIONS": {"max_similarity": 0.7},  # na razie tylko parametr informacyjny
    },
    {
        "NAME": "app.core.validators.CommonPasswordListValidator",
        # Możesz dodać zewnętrzny plik z listą haseł:
        # "OPTIONS": {"common_passwords_file": BASE_DIR / "common_passwords.txt"},
    },
    {
        "NAME": "app.core.validators.ComplexityScoreValidator",
        "OPTIONS": {"min_score": 4},
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True

AUTHENTICATION_BACKENDS = (
    'app.core.auth_backends.RoleViewPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = "optional"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    ("assets", BASE_DIR / "templates" / "assets"),
]

MEDIA_ROOT = os.path.join(BASE_DIR, "files")
MEDIA_URL = "/files/"
# Must match the internal-only Nginx location.
PRIVATE_MEDIA_INTERNAL_URL = "/_protected_media/"
FILE_UPLOAD_PERMISSIONS = 0o640
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o750

# settings.py
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_IDS = {
    "start": {
        "monthly": os.getenv("STRIPE_PRICE_START_MONTHLY", ""),
        "yearly": os.getenv("STRIPE_PRICE_START_YEARLY", ""),
    },
    "standard": {
        "monthly": os.getenv("STRIPE_PRICE_STANDARD_MONTHLY", ""),
        "yearly": os.getenv("STRIPE_PRICE_STANDARD_YEARLY", ""),
    },
    "pro": {
        "monthly": os.getenv("STRIPE_PRICE_PRO_MONTHLY", ""),
        "yearly": os.getenv("STRIPE_PRICE_PRO_YEARLY", ""),
    },
}
STRIPE_PLAN_PRICE_AMOUNTS = {
    "start": {
        "monthly": int(os.getenv("STRIPE_AMOUNT_START_MONTHLY", "0") or 0),
        "yearly": int(os.getenv("STRIPE_AMOUNT_START_YEARLY", "0") or 0),
    },
    "standard": {
        "monthly": int(os.getenv("STRIPE_AMOUNT_STANDARD_MONTHLY", "0") or 0),
        "yearly": int(os.getenv("STRIPE_AMOUNT_STANDARD_YEARLY", "0") or 0),
    },
    "pro": {
        "monthly": int(os.getenv("STRIPE_AMOUNT_PRO_MONTHLY", "0") or 0),
        "yearly": int(os.getenv("STRIPE_AMOUNT_PRO_YEARLY", "0") or 0),
    },
}
if not DEBUG and any(
    not price_id
    for plan_prices in STRIPE_PRICE_IDS.values()
    for price_id in plan_prices.values()
):
    raise ImproperlyConfigured("Set all six STRIPE_PRICE_* variables before production startup.")
if not DEBUG and any(
    amount <= 0
    for plan_amounts in STRIPE_PLAN_PRICE_AMOUNTS.values()
    for amount in plan_amounts.values()
):
    raise ImproperlyConfigured("Set all six STRIPE_AMOUNT_* variables before production startup.")
# Pin outbound Stripe requests to the API contract used by this integration.
STRIPE_API_VERSION = "2024-09-30.acacia"

# przyda się do budowania success/cancel URL
DOMAIN_URL = os.getenv("DOMAIN_URL", f"https://{PANEL_DOMAIN}").rstrip("/")

# Cena jednego dodatkowego użytkownika w groszach.
STRIPE_EXTRA_USER_UNIT_AMOUNTS = {
    "monthly": 2500,
    "yearly": 25000,
}

# Zadania okresowe subskrypcji. W środowisku produkcyjnym muszą działać
# procesy Celery worker oraz Celery beat.
from celery.schedules import crontab

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    "subscription-lifecycle-daily": {
        "task": "app.core.tasks.process_subscription_lifecycle",
        "schedule": 24 * 60 * 60,
    },
    "leave-allowances-yearly": {
        "task": "app.urlop.tasks.generate_leave_allowances_for_year",
        "schedule": crontab(minute=15, hour=0, day_of_month=1, month_of_year=1),
    },
    "supplier-integrations-sync": {
        "task": "app.dostawcy.tasks.sync_active_supplier_integrations",
        "schedule": crontab(minute=30, hour=3),
    },
}

# Klucz dla zaszyfrowanych URL-i feedów. W środowisku produkcyjnym ustaw go
# niezależnie od SECRET_KEY, aby rotacja klucza sesji nie unieważniała feedów.
SUPPLIER_FEED_ENCRYPTION_KEY = os.getenv("SUPPLIER_FEED_ENCRYPTION_KEY", SECRET_KEY)


EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True").lower() in {"1", "true", "yes", "on"}
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Dapexa <no-reply@dapexa.com>")

SITE_ID = 1

ORS_API_KEY = os.getenv("ORS_API_KEY", "")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")

WKHTMLTOPDF_CMD = '/usr/local/bin/wkhtmltopdf'
