# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_address_options_alter_company_options_and_more'),
        ('klient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona'), ('expired', 'Przedawniona')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='klient.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='szt.', max_length=20)),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=23, max_digits=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oferta_praca.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
