# Generated by Django 5.0.6 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oferta_praca', '0001_initial'),
        ('urzadzenie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urzadzenie.product'),
        ),
    ]
