# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.AlterModelOptions(
            name='offeritem',
            options={'verbose_name': 'Przedmiot oferty', 'verbose_name_plural': 'Przedmiot oferty'},
        ),
    ]
