# Generated by Django 6.0.3 on 2026-03-31 19:23

import app.oferta_praca.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('oferta_praca', '0003_alter_offer_options_alter_offeritem_options'),
        ('urzadzenie', '0002_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVariantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=app.oferta_praca.models.offer_variant_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfferVariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('material', 'Materiał'), ('accessory', 'Akcesoria'), ('labor', 'Robocizna'), ('service', 'Usługa'), ('other', 'Inne')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='szt.', max_length=20)),
                ('unit_price_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=23, max_digits=5)),
                ('total_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='offeritem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offeritem',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offeritem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-issue_date', '-id']},
        ),
        migrations.AddField(
            model_name='offer',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='klient.client'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='OfferVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('materials_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accessories_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('services_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='oferta_praca.offer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='selected_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_offers', to='oferta_praca.offervariant'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_offer_number_per_company'),
        ),
        migrations.AddField(
            model_name='offervariantfile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company'),
        ),
        migrations.AddField(
            model_name='offervariantfile',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='oferta_praca.offervariant'),
        ),
        migrations.AddField(
            model_name='offervariantitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company'),
        ),
        migrations.AddField(
            model_name='offervariantitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_items', to='urzadzenie.product'),
        ),
        migrations.AddField(
            model_name='offervariantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oferta_praca.offervariant'),
        ),
        migrations.DeleteModel(
            name='OfferItem',
        ),
        migrations.AddConstraint(
            model_name='offervariant',
            constraint=models.UniqueConstraint(fields=('offer', 'name'), name='unique_variant_name_per_offer'),
        ),
    ]
