# Generated by Django 6.0.3 on 2026-03-31 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('oferta_praca', '0004_offervariantfile_offervariantitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-issue_date', '-id'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
        migrations.AlterModelOptions(
            name='offervariant',
            options={'ordering': ['id'], 'verbose_name': 'Wariant oferty', 'verbose_name_plural': 'Warianty ofert'},
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zatwierdzenia'),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdził'),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_by_manager',
            field=models.BooleanField(default=False, verbose_name='Czy oferta zatwierdzona przez szefa/menadżera'),
        ),
        migrations.AddField(
            model_name='offer',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_offers', to=settings.AUTH_USER_MODEL, verbose_name='Przypisani pracownicy'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='offer',
            name='employees_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ilu pracowników'),
        ),
        migrations.AddField(
            model_name='offer',
            name='execution_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Ilość dni na wykonanie'),
        ),
        migrations.AddField(
            model_name='offer',
            name='forwarded_to_execution_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data przekazania do realizacji'),
        ),
        migrations.AddField(
            model_name='offer',
            name='has_service',
            field=models.BooleanField(default=False, verbose_name='Czy jest obsługa'),
        ),
        migrations.AddField(
            model_name='offer',
            name='has_warranty',
            field=models.BooleanField(default=False, verbose_name='Czy jest gwarancja'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Czy zamówiono'),
        ),
        migrations.AddField(
            model_name='offer',
            name='labor_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ilość roboczogodzin'),
        ),
        migrations.AddField(
            model_name='offer',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numer zamówienia'),
        ),
        migrations.AddField(
            model_name='offer',
            name='sent_to_client_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data wysłania do klienta'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='klient.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='issue_date',
            field=models.DateField(verbose_name='Data wystawienia'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Numer oferty'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='selected_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_offers', to='oferta_praca.offervariant', verbose_name='Wybrany wariant'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Spotkanie'), (1, 'Do zrobienia'), (2, 'Przygotowane'), (3, 'Wysłane'), (4, 'Nieaktualne'), (5, 'Przekazane do realizacji'), (7, 'Nowe'), (8, 'Do zatwierdzenia')], default=7, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ważna do'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='accessories_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Akcesoria netto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='labor_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Robocizna netto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='materials_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Materiały netto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nazwa wariantu'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='oferta_praca.offer', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='other_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Inne netto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='services_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Usługi netto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='total_brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Razem brutto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='total_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Razem netto'),
        ),
        migrations.AlterField(
            model_name='offervariant',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='VAT'),
        ),
    ]
