# Generated by Django 6.0.3 on 2026-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0005_alter_offer_options_alter_offervariant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='selected_variant',
        ),
        migrations.AddField(
            model_name='offer',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data wykonania'),
        ),
        migrations.AddField(
            model_name='offer',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zamówienia'),
        ),
        migrations.AddField(
            model_name='offer',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('normal', 'Normalny'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], default='normal', max_length=10, verbose_name='Priorytet'),
        ),
        migrations.AddField(
            model_name='offervariant',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Wybrany'),
        ),
        migrations.AddField(
            model_name='offervariant',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wyboru'),
        ),
    ]
