# Generated by Django 6.0.3 on 2026-03-31 19:42

import app.oferta_praca.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('oferta_praca', '0006_remove_offer_selected_variant_offer_execution_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to=app.oferta_praca.models.offer_image_file_path, verbose_name='Zdjęcie')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='oferta_praca.offer', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Zdjęcie oferty',
                'verbose_name_plural': 'Zdjęcia ofert',
                'ordering': ['sort_order', '-uploaded_at', '-id'],
            },
        ),
    ]
