# Generated by Django 6.0.3 on 2026-03-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0007_offerimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerimage',
            options={'ordering': ['-uploaded_at', '-id'], 'verbose_name': 'Zdjęcie oferty', 'verbose_name_plural': 'Zdjęcia ofert'},
        ),
        migrations.RemoveField(
            model_name='offerimage',
            name='sort_order',
        ),
    ]
