# Generated by Django 6.0.3 on 2026-03-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('oferta_praca', '0008_alter_offerimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='klient.clientlocation', verbose_name='Lokalizacja'),
        ),
        migrations.CreateModel(
            name='OfferNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_counters', to='core.company')),
            ],
            options={
                'verbose_name': 'Licznik numerów ofert',
                'verbose_name_plural': 'Liczniki numerów ofert',
                'unique_together': {('company', 'year')},
            },
        ),
    ]
