# Generated by Django 6.0.3 on 2026-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0009_offer_location_offernumbercounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Spotkanie'), (7, 'Do zrobienia'), (2, 'Przygotowane'), (3, 'Wysłane'), (4, 'Nieaktualne'), (5, 'Przekazane do realizacji'), (1, 'Nowe'), (8, 'Do zatwierdzenia')], default=1, verbose_name='Status'),
        ),
    ]
