# Generated by Django 6.0.3 on 2026-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0010_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offervariant',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('items', 'Pozycje')], default='items', max_length=10, verbose_name='Sposób utworzenia'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nowe'), (6, 'Spotkanie'), (7, 'Do zrobienia'), (2, 'Przygotowane'), (3, 'Wysłane'), (4, 'Nieaktualne'), (5, 'Przekazane do realizacji')], default=1, verbose_name='Status'),
        ),
    ]
