# Generated by Django 6.0.3 on 2026-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0011_offervariant_source_type_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offervariantitem',
            name='item_type',
            field=models.CharField(choices=[('material', 'Materiał'), ('accessory', 'Akcesoria'), ('service', 'Usługa')], max_length=20),
        ),
    ]
