# Generated by Django 6.0.3 on 2026-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0012_alter_offervariantitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data i czas spotkania'),
        ),
    ]
