# Generated by Django 6.0.3 on 2026-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0013_offer_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='post_meeting_notes',
            field=models.TextField(blank=True, verbose_name='Informacje po spotkaniu'),
        ),
    ]
