# Generated by Django 6.0.3 on 2026-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0014_offer_post_meeting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Powód odrzucenia / nieaktualności'),
        ),
    ]
