# Generated by Django 6.0.3 on 2026-05-01 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('oferta_praca', '0015_offer_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('note', 'Notatka'), ('status', 'Zmiana statusu'), ('variant', 'Wariant'), ('file', 'Plik'), ('image', 'Zdjęcie'), ('workers', 'Pracownicy'), ('priority', 'Priorytet'), ('approval', 'Zatwierdzenie'), ('system', 'System')], default='system', max_length=20, verbose_name='Typ')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_activities', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='oferta_praca.offer', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Historia oferty',
                'verbose_name_plural': 'Historia ofert',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
