# Generated by Django 6.0.3 on 2026-05-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_alter_document_options_alter_documentfolder_options'),
        ('oferta_praca', '0016_offeractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_images', related_query_name='offer_image', to='dokument.documentfolder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='offervariantfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_variant_files', related_query_name='offer_variant_file', to='dokument.documentfolder', verbose_name='Folder'),
        ),
    ]
