# Generated by Django 6.0.3 on 2026-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0017_offerimage_folder_offervariantfile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='offervariant',
            name='sale_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cena sprzedaży netto'),
        ),
    ]
