# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
import app.oferta_praca.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_praca', '0020_alter_offer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar zdjęcia'),
        ),
        migrations.AddField(
            model_name='offervariantfile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar pliku'),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='file',
            field=app.core.fields.TrackedImageField(upload_to=app.oferta_praca.models.offer_image_file_path, verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='offervariantfile',
            name='file',
            field=app.core.fields.TrackedFileField(upload_to=app.oferta_praca.models.offer_variant_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
