# Generated by Django 5.0.6 on 2025-11-25 22:05

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paneluser',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterModelManagers(
            name='paneluser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='paneluser',
            name='username',
        ),
        migrations.AddField(
            model_name='paneluser',
            name='avatar',
            field=models.FileField(blank=True, default='avatary/1.png', max_length=500, null=True, upload_to=app.core.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='badania_lekarskie',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='badania_lekarskie_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mężczyzna'), (2, 'Kobieta')], default=1),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='prawko',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='wyksztalcenie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paneluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='paneluser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='paneluser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
