# Generated by Django 5.0.6 on 2025-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paneluser_options_alter_paneluser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmy'},
        ),
        migrations.AddField(
            model_name='paneluser',
            name='phone_priv',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
