# Generated by Django 5.0.6 on 2025-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Miesięcznie'), ('yearly', 'Rocznie')], help_text='Okres rozliczenia (ustawiany dopiero przy płatnym pakiecie).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.CharField(choices=[('trial', 'Trial'), ('start', 'Start'), ('standard', 'Standard'), ('pro', 'Pro')], default='trial', help_text='Pakiet: trial / start / standard / pro', max_length=20),
        ),
    ]
