# Generated by Django 5.0.6 on 2026-02-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_billing_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_cost_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Koszt dojazdu za 1 km', max_digits=8)),
                ('labor_price_1_worker', models.DecimalField(decimal_places=2, default=0, help_text='Cena za 1 pracownika', max_digits=10)),
                ('labor_price_2_workers', models.DecimalField(decimal_places=2, default=0, help_text='Cena za 2 pracowników', max_digits=10)),
                ('labor_price_3_workers', models.DecimalField(decimal_places=2, default=0, help_text='Cena za 3 pracowników', max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_vat', models.DecimalField(decimal_places=2, default=23, max_digits=4)),
                ('default_protocol_valid_days', models.IntegerField(default=14)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
