# Generated by Django 5.0.6 on 2026-02-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company'),
        ),
    ]
