# Generated by Django 5.0.6 on 2026-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('origin_lat', 'origin_lng', 'dest_lat', 'dest_lng')},
            },
        ),
    ]
