# Generated by Django 5.0.6 on 2026-02-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_routedistancecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneluser',
            name='employment_fraction',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Wymiar etatu (np. 1.00, 0.50)'),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zatrudnienia'),
        ),
        migrations.AddField(
            model_name='paneluser',
            name='previous_employment_years',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Staż z poprzednich miejsc pracy (lata)'),
        ),
        migrations.AlterField(
            model_name='paneluser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paneluser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
