# Generated by Django 6.0.3 on 2026-03-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paneluser_employment_fraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneluser',
            name='role',
            field=models.CharField(choices=[('owner', 'Właściciel'), ('manager', 'Manager'), ('biuro', 'Biuro'), ('employee', 'Pracownik'), ('client', 'Klient')], default='employee', max_length=20),
        ),
    ]
