# Generated by Django 6.0.3 on 2026-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
