# Generated by Django 6.0.3 on 2026-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_address_street_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneluser',
            name='role',
            field=models.CharField(choices=[('owner', 'Właściciel'), ('manager', 'Manager'), ('biuro', 'Biuro'), ('podwykonawca', 'Podwykonawca'), ('employee', 'Pracownik'), ('client', 'Klient')], default='employee', max_length=20),
        ),
    ]
