# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_paneluser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneluser',
            name='avatar_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar avatara'),
        ),
        migrations.AlterField(
            model_name='paneluser',
            name='avatar',
            field=app.core.fields.TrackedFileField(blank=True, default='avatary/1.png', max_length=500, null=True, upload_to=app.core.models.user_directory_path),
        ),
    ]
