# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_paneluser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paneluser",
            name="two_factor_enabled",
            field=models.BooleanField(default=True, verbose_name="Weryfikacja dwuetapowa"),
        ),
        migrations.AddField(
            model_name="paneluser",
            name="login_2fa_code_hash",
            field=models.CharField(blank=True, max_length=255, verbose_name="Hash kodu 2FA logowania"),
        ),
        migrations.AddField(
            model_name="paneluser",
            name="login_2fa_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ważność kodu 2FA logowania"),
        ),
        migrations.AddField(
            model_name="paneluser",
            name="login_2fa_attempts",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Liczba prób kodu 2FA logowania"),
        ),
    ]
