# Generated by Codex on 2026-07-15

from django.db import migrations


def disable_2fa_for_active_users(apps, schema_editor):
    PanelUser = apps.get_model("core", "PanelUser")
    PanelUser.objects.filter(is_active=True).update(two_factor_enabled=False)


def enable_2fa_for_active_users(apps, schema_editor):
    PanelUser = apps.get_model("core", "PanelUser")
    PanelUser.objects.filter(is_active=True).update(two_factor_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_paneluser_two_factor_login"),
    ]

    operations = [
        migrations.RunPython(
            disable_2fa_for_active_users,
            enable_2fa_for_active_users,
        ),
    ]
