# Generated by Codex on 2026-07-15

import app.core.fields
import app.core.models
from django.db import migrations


def clear_old_default_avatar(apps, schema_editor):
    PanelUser = apps.get_model("core", "PanelUser")
    PanelUser.objects.filter(avatar__in=["avatary/1.png", "Avatary/1.png"]).update(
        avatar="",
        avatar_size=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_disable_2fa_for_active_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paneluser",
            name="avatar",
            field=app.core.fields.TrackedFileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=app.core.models.user_directory_path,
            ),
        ),
        migrations.RunPython(clear_old_default_avatar, migrations.RunPython.noop),
    ]
