# Generated by Codex on 2026-07-15

import app.core.fields
import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_paneluser_avatar_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=app.core.fields.TrackedFileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=app.core.models.company_logo_directory_path,
                verbose_name="Logo firmy",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_size",
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                help_text="Rozmiar zapisany w bajtach.",
                verbose_name="Rozmiar loga firmy",
            ),
        ),
    ]
