# Generated by Django 6.0.3 on 2026-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='maintenance_number_prefix',
            field=models.CharField(default='OBS', max_length=12, verbose_name='Prefiks numeru obsługi'),
        ),
    ]
