# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urzadzenie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Urzadzenie', 'verbose_name_plural': 'Urzadzenia'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Kategoria urzadzenia', 'verbose_name_plural': 'Kategoria urzadzenia'},
        ),
    ]
