# Generated by Django 6.0.3 on 2026-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urzadzenie', '0002_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('material', 'Materiał'), ('service', 'Usługa'), ('accessory', 'Akcesoria'), ('labor', 'Robocizna'), ('other', 'Inne')], default='material', max_length=20),
        ),
    ]
