# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urzadzenie', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar zdjęcia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=app.core.fields.TrackedImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
