# Generated by Django 6.0.3 on 2026-05-02 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_paneluser_role'),
        ('klient', '0011_remove_clientlocation_email_and_more'),
        ('oferta_praca', '0016_offeractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Numer pracy')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W realizacji'), ('done', 'Zakończone'), ('cancelled', 'Anulowane')], default='new', max_length=20, verbose_name='Status')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Planowana data rozpoczęcia')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Planowana data zakończenia')),
                ('employees_count', models.PositiveIntegerField(default=0, verbose_name='Ilu pracowników')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Roboczogodziny')),
                ('execution_days', models.PositiveIntegerField(default=0, verbose_name='Dni na wykonanie')),
                ('total_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employees', models.ManyToManyField(blank=True, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Przypisani pracownicy')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='klient.client', verbose_name='Klient')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='klient.clientlocation', verbose_name='Lokalizacja')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='oferta_praca.offer', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Praca',
                'verbose_name_plural': 'Prace',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
    ]
