# Generated by Django 6.0.3 on 2026-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Czy zamówiono'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numer zamówienia'),
        ),
    ]
