# Generated by Django 6.0.3 on 2026-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praca', '0003_workactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planowana data zakończenia'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planowana data rozpoczęcia'),
        ),
    ]
