# Generated by Django 5.0.6 on 2025-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterModelOptions(
            name='documentfolder',
            options={'verbose_name': 'Folder na dokument', 'verbose_name_plural': 'Folder na dokumenty'},
        ),
    ]
