# Generated by Django 6.0.3 on 2026-07-06 17:21

import app.core.fields
import app.dokument.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0004_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Rozmiar zapisany w bajtach.', verbose_name='Rozmiar pliku'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=app.core.fields.TrackedFileField(upload_to=app.dokument.models.company_document_path),
        ),
    ]
