MODULES = [
    {
        "slug": "klienci", "name": "Klienci", "icon": "bi-people", "color": "blue",
        "summary": "Kartoteki klientów, kontakty, adresy, lokalizacje, notatki i historia.",
        "sections": [
            ("Cel modułu", ["Moduł przechowuje dane osób prywatnych i firm oraz wszystkie realizacje powiązane z klientem."]),
            ("Najważniejsze funkcje", ["Dodawanie i edycja klienta, opiekun, adres wysyłkowy i rozliczeniowy, osoby kontaktowe, lokalizacje, notatki, historia, serwisy, prace i protokoły."]),
            ("Proces pracy", ["Dodaj klienta, uzupełnij poprawny adres, otwórz kartę szczegółów, a następnie dodawaj lokalizacje i informacje dodatkowe. Klienta można zarchiwizować zamiast usuwać."]),
            ("Uprawnienia", ["klient_add, klient_edit, klient_detail, klient_delete, klient_deactivate, klient_activate, client_note_pin, client_note_delete, contact_person_add, location_add, location_edit, location_delete."]),
        ],
    },
    {
        "slug": "serwisy", "name": "Serwisy", "icon": "bi-tools", "color": "orange", "summary": "Zgłoszenia serwisowe, planowanie realizacji i dzienne rozliczenia.",
        "sections": [("Cel modułu", ["Rejestrowanie zgłoszeń i prowadzenie realizacji u klienta."]), ("Najważniejsze funkcje", ["Rodzaj Serwis lub Obsługa, priorytet, klient, lokalizacja, termin, pracownicy, załączniki, notatki, statusy i protokół."]), ("Rozliczenie godzinowe", ["Dzienny wpis zawiera datę, godziny, osoby, dojazd, materiał i wykonane prace. Wpisuje go automatycznie zalogowany pracownik."]), ("Uprawnienia", ["serwis_nowe, serwis_add, serwis_detail, serwis_edit, serwis_delete, serwis_status_update, serwis_schedule_update, serwis_assign_workers, service_work_log_add."])],
    },
    {
        "slug": "protokoly", "name": "Protokoły", "icon": "bi-file-earmark-text", "color": "orange", "summary": "Protokoły odbioru prac i dokumenty PDF.",
        "sections": [("Cel modułu", ["Potwierdzenie wykonania serwisu lub pracy i zebranie danych do faktury."]), ("Proces", ["Utwórz protokół z serwisu/pracy, dodaj klienta, urządzenia, opis, robociznę, materiały i podpisy. Następnie wygeneruj PDF lub przekaż do fakturowania."]), ("Statusy", ["Nowy, do zafakturowania, wysłany i pozostałe statusy procesu."]), ("Uprawnienia", ["protokol_nowe, protokol_add, protokol_detail, protokol_edit, protokol_delete, protokol_invoice."])],
    },
    {
        "slug": "oferty", "name": "Oferty", "icon": "bi-file-earmark-richtext", "color": "blue", "summary": "Oferty pracy z wariantami i pozycjami kosztowymi.",
        "sections": [("Cel modułu", ["Przygotowanie propozycji realizacji przed utworzeniem pracy."]), ("Warianty", ["Oferta może mieć wiele wariantów. Wariant zawiera materiały, akcesoria, usługi, cenę, zysk i pliki. Wybrany wariant jest uwzględniany przy przekazaniu do realizacji."]), ("Przekazanie", ["Po zatwierdzeniu oferty wybierz przekazanie do realizacji. System tworzy pracę na podstawie wybranego wariantu."]), ("Uprawnienia", ["offer_list, offer_add, offer_detail, offer_update, offer_delete, offer_variant_create, offer_variant_update."])],
    },
    {
        "slug": "prace", "name": "Prace", "icon": "bi-hammer", "color": "orange", "summary": "Planowanie i realizacja prac przypisanych do klientów i pracowników.",
        "sections": [("Cel modułu", ["Obsługa prac utworzonych ręcznie lub przekazanych z oferty."]), ("Szczegóły", ["Praca zawiera klienta, termin, pracowników, status, opis, zamówiony sprzęt, koszty oraz historię."]), ("Statusy", ["Nowe, w realizacji, zakończone i anulowane. Pracownik może zmieniać status zgodnie z nadanym uprawnieniem."]), ("Uprawnienia", ["workorder_list, workorder_add, workorder_detail, workorder_update, workorder_delete, work_schedule_update, work_assign_workers, work_status_update."])],
    },
    {
        "slug": "obsluga", "name": "Obsługa", "icon": "bi-gear-wide-connected", "color": "blue", "summary": "Umowy stałej obsługi, urządzenia i parametry umów.",
        "sections": [("Cel modułu", ["Zarządzanie stałą obsługą urządzeń klientów."]), ("Umowy", ["Utwórz umowę, przypisz klienta, urządzenia, terminy i parametry. Historia pokazuje zmiany i działania."]), ("Elementy", ["Do umowy można dodawać, edytować i usuwać urządzenia oraz parametry."]), ("Uprawnienia", ["service_contract_list, service_contract_add, service_contract_detail, service_contract_update, service_contract_delete, service_contract_asset_add, service_contract_parameter_add."])],
    },
    {
        "slug": "gwarancje", "name": "Gwarancje", "icon": "bi-shield-check", "color": "orange", "summary": "Zgłoszenia gwarancyjne do dostawców i hurtowni.",
        "sections": [("Cel modułu", ["Rejestrowanie usterek urządzeń i prowadzenie zgłoszeń gwarancyjnych."]), ("Formularz", ["Wybierz klienta, lokalizację, urządzenie i dostawcę. Dodaj opis usterki, notatki oraz zdjęcia."]), ("Szczegóły", ["Karta zgłoszenia zawiera status, historię, pliki i akcje obsługi."]), ("Uprawnienia", ["warranty_claim_list, warranty_claim_add, warranty_claim_detail, warranty_claim_update, warranty_claim_delete."])],
    },
    {
        "slug": "zadania", "name": "Zadania", "icon": "bi-check2-square", "color": "blue", "summary": "Zadania indywidualne, grupowe i firmowe.",
        "sections": [("Cel modułu", ["Planowanie spraw do wykonania przez osobę, rolę albo wszystkich użytkowników."]), ("Praca z zadaniem", ["Ustaw tytuł, opis, termin i adresata. Zadania po terminie są oznaczane na dashboardzie. Po wykonaniu znikają z listy otwartych."]), ("Widoki", ["Lista zadań, szczegóły, statusy i zadania przypisane użytkownikowi."]), ("Uprawnienia", ["task_list, task_add, task_detail, task_update, task_delete, task_complete."])],
    },
    {
        "slug": "pojazdy", "name": "Pojazdy", "icon": "bi-truck", "color": "orange", "summary": "Ewidencja pojazdów, terminów OC, przeglądów i zdarzeń.",
        "sections": [("Dane pojazdu", ["Numer rejestracyjny, marka, model, VIN, przebieg i zdjęcie."]), ("Terminy", ["Pola OC i przeglądu są używane w alertach dashboardu oraz kalendarzu."]), ("Zdarzenia", ["Dodaj naprawę, serwis, szkodę, przegląd, ubezpieczenie lub inne zdarzenie. Zmiany są zapisywane w historii."]), ("Uprawnienia", ["vehicle_list, vehicle_create, vehicle_detail, vehicle_update, vehicle_delete, vehicle_event_create, vehicle_event_update, vehicle_event_delete."])],
    },
    {
        "slug": "sprzet", "name": "Sprzęt", "icon": "bi-wrench-adjustable", "color": "blue", "summary": "Ewidencja sprzętu firmowego i jego zdarzeń.",
        "sections": [("Cel modułu", ["Prowadzenie rejestru sprzętu używanego w firmie i przy realizacjach."]), ("Dane", ["Nazwa, numer, opis, status, zdjęcie i dokumenty."]), ("Zdarzenia", ["Do sprzętu można dodawać zdarzenia, koszty, opis i załączniki. Historia pokazuje zmiany."]), ("Uprawnienia", ["tool_list, tool_create, tool_detail, tool_update, tool_delete, tool_event_create."])],
    },
    {
        "slug": "urzadzenia", "name": "Urządzenia", "icon": "bi-cpu", "color": "orange", "summary": "Katalog urządzeń klientów i urządzeń używanych w realizacjach.",
        "sections": [("Cel modułu", ["Centralny katalog urządzeń z numerami seryjnymi i danymi technicznymi."]), ("Powiązania", ["Urządzenie może być przypisane do klienta, lokalizacji, serwisu, gwarancji lub protokołu."]), ("Wyszukiwanie", ["Formularze protokołów i zgłoszeń mogą wyszukiwać urządzenia przez AJAX."]), ("Uprawnienia", ["product_list, product_create, product_detail, product_update, product_delete."])],
    },
    {
        "slug": "magazyn", "name": "Magazyn", "icon": "bi-box-seam", "color": "blue", "summary": "Magazyny, stany i ruchy materiałowe.",
        "sections": [("Cel modułu", ["Kontrola ilości materiałów i sprzętu znajdującego się w magazynach."]), ("Magazyn", ["Utwórz magazyn, określ nazwę i dane podstawowe."]), ("Ruchy", ["Dodawaj przyjęcia, wydania i korekty. Stan jest wyliczany na podstawie ruchów."]), ("Uprawnienia", ["stock_list, stock_create, stock_detail, stock_update, stock_delete, stock_movement_add."])],
    },
    {
        "slug": "rcp", "name": "RCP", "icon": "bi-clock-history", "color": "orange", "summary": "Rejestracja czasu pracy i wnioski o korektę.",
        "sections": [("Wpis czasu", ["Wpisz datę, rozpoczęcie, zakończenie i opis. Domyślne godziny wynikają z ustawień firmy."]), ("Akceptacja", ["Czasy pracy mogą być zatwierdzane przez osoby uprawnione. Zatwierdzone wpisy trafiają do raportów."]), ("Urlopy", ["System blokuje dodawanie czasu pracy w dniach zatwierdzonego urlopu."]), ("Uprawnienia", ["time_entry_list, time_entry_create, time_entry_update, time_entry_request_list, time_entry_request_approve."])],
    },
    {
        "slug": "kalendarz", "name": "Kalendarz", "icon": "bi-calendar3", "color": "blue", "summary": "Serwisy, prace, urlopy i własne wydarzenia w jednym miejscu.",
        "sections": [("Widoki", ["Na komputerze dostępne są dzień, tydzień i miesiąc. Na telefonie pozostaje widok dnia."]), ("Wydarzenia", ["Kalendarz pokazuje przypisane serwisy i prace, urlopy pracowników oraz wydarzenia całodniowe."]), ("Własne wpisy", ["Dodaj własne wydarzenie z nazwą, datą, godziną i opisem. Własne wydarzenie można usunąć."]), ("Ograniczenia", ["Weekendy są ukryte, a godziny są ograniczone do domyślnego zakresu pracy firmy."])],
    },
    {
        "slug": "urlopy", "name": "Urlopy", "icon": "bi-calendar-plus", "color": "orange", "summary": "Wnioski urlopowe, limity i akceptacja nieobecności.",
        "sections": [("Wniosek", ["Pracownik wybiera rodzaj urlopu, zakres dat i opcjonalny powód."]), ("Akceptacja", ["Osoba uprawniona zatwierdza albo odrzuca wniosek. Zatwierdzony urlop jest widoczny w kalendarzu."]), ("Anulowanie", ["Zatwierdzony urlop można anulować. Anulowanie zwraca wykorzystane dni do limitu."]), ("Uprawnienia", ["urlop_add, leave_list, hr_leave_list, leave_approve, leave_cancel, leave_allowance_list."])],
    },
    {
        "slug": "pracownicy", "name": "Pracownicy", "icon": "bi-person-badge", "color": "blue", "summary": "Konta, role, uprawnienia, umowy i szkolenia pracowników.",
        "sections": [("Konta", ["Dodaj pracownika, ustaw dane, rolę i aktywność konta. Możliwe jest ustawienie pierwszego hasła."]), ("Role i grupy", ["Twórz grupy uprawnień i przypisuj pracowników. Uprawnienia są kontrolowane w widokach i przyciskach."]), ("Profil", ["Pracownik może zarządzać 2FA, umowami, szkoleniami i własnymi danymi zgodnie z rolą."]), ("Bezpieczeństwo", ["Właściciel może przekazać własność firmy z potwierdzeniem e-mailowym."])],
    },
    {
        "slug": "ustawienia-firmy", "name": "Ustawienia firmy", "icon": "bi-building-gear", "color": "orange", "summary": "Dane firmy i wartości domyślne używane w dokumentach oraz formularzach.",
        "sections": [("Dane firmy", ["Nazwa, NIP, REGON, KRS, kontakt i logo firmy."]), ("Konfiguracja", ["Adres, godziny pracy RCP, ustawienia rozliczeń, numeracja protokołów i numeracja serwisów."]), ("Powiadomienia", ["Ustaw adresy e-mail modułów oraz preferencje powiadomień użytkowników."]), ("Pakiety", ["Limity użytkowników, plików i pamięci są egzekwowane zgodnie z aktywnym pakietem."])],
    },
    {
        "slug": "dokumenty", "name": "Dokumenty", "icon": "bi-folder", "color": "blue", "summary": "Foldery i pliki firmowe z kontrolą rozmiaru oraz limitu pamięci.",
        "sections": [("Pliki", ["Dodawaj dokumenty i zdjęcia, przeglądaj je oraz korzystaj z powiązań z rekordami."]), ("Foldery", ["Porządkuj pliki według modułów, klientów i typów dokumentów."]), ("Limity", ["Każdy plik ma zapisaną wagę, a suma danych jest porównywana z limitem pakietu firmy."])],
    },
    {
        "slug": "faktury", "name": "Faktury", "icon": "bi-receipt", "color": "orange", "summary": "Dokumenty sprzedaży i fakturowanie wykonanych realizacji.",
        "sections": [("Tworzenie", ["Fakturę można utworzyć z danych protokołu i uzupełnić pozycje sprzedaży."]), ("Kwoty", ["System rozróżnia wartości netto, VAT i brutto oraz zapisuje podsumowanie."]), ("Numeracja", ["Numer dokumentu korzysta z ustawień numeracji firmy."]), ("Proces", ["Protokół do zafakturowania jest źródłem danych dla nowej faktury i zmienia status po obsłużeniu."])],
    },
    {
        "slug": "wsparcie-techniczne", "name": "Wsparcie techniczne", "icon": "bi-headset", "color": "blue", "summary": "Zgłaszanie pytań, problemów i próśb o pomoc dotyczącą działania systemu.",
        "sections": [("Zakres modułu", ["Moduł służy do przekazywania problemów technicznych, pytań dotyczących funkcji oraz sugestii usprawnień do zespołu wsparcia."]), ("Zgłoszenie", ["Użytkownik powinien opisać problem, wskazać moduł, którego dotyczy, podać kroki odtworzenia oraz dołączyć zrzut ekranu lub plik, jeśli ułatwi to diagnozę."]), ("Status obsługi", ["Zgłoszenie może być nowe, w trakcie analizy, oczekujące na informacje albo rozwiązane. Odpowiedzi i zmiany statusu powinny być widoczne w historii zgłoszenia."])],
    },
]

# Nazwy są prezentowane użytkownikom, a kody odpowiadają permissionom Django.
MODULE_META = {
    "klienci": {"permissions": [("access_klient", "Wyświetla listę klientów"), ("access_klient_add", "Dodaje klienta"), ("access_klient_edit", "Edytuje dane klienta"), ("access_klient_detail", "Otwiera szczegóły klienta"), ("access_klient_delete", "Trwale usuwa klienta"), ("access_klient_deactivate / activate", "Archiwizuje i przywraca klienta"), ("location_add / edit / delete", "Zarządza lokalizacjami")], "buttons": [("Dodaj klienta", "Otwiera formularz nowego klienta."), ("Szczegóły", "Otwiera kartę klienta."), ("Edytuj", "Zmienia dane klienta i adresy."), ("Archiwizuj / Przywróć", "Zmienia aktywność klienta."), ("Usuń", "Trwale usuwa klienta po potwierdzeniu.")]},
    "serwisy": {"permissions": [("access_serwis_nowe", "Wyświetla listę serwisów"), ("access_serwis_add", "Dodaje zgłoszenie"), ("access_serwis_detail", "Otwiera szczegóły"), ("access_serwis_edit / delete", "Edytuje i usuwa zgłoszenie"), ("access_serwis_schedule_update", "Ustala termin"), ("access_serwis_assign_workers", "Przypisuje pracowników"), ("access_service_work_log_add", "Dodaje dzienne rozliczenie")], "buttons": [("Dodaj serwis", "Tworzy zgłoszenie Serwis lub Obsługa."), ("Ustal termin", "Otwiera planowanie startu i końca."), ("Wyznacz pracowników", "Przypisuje osoby do realizacji."), ("Dodaj wpis", "Dodaje dzienne rozliczenie godzinowe."), ("Utwórz protokół", "Kończy realizację i rozpoczyna protokół.")]},
    "protokoly": {"permissions": [("access_protokol_nowe", "Wyświetla listę protokołów"), ("access_protokol_add", "Tworzy protokół"), ("access_protokol_detail", "Otwiera szczegóły"), ("access_protokol_edit / delete", "Edytuje i usuwa protokół"), ("access_protokol_invoice", "Przekazuje do fakturowania")], "buttons": [("Nowy protokół", "Otwiera formularz protokołu."), ("Edytuj", "Zmienia dane protokołu."), ("PDF", "Generuje dokument protokołu."), ("Zafakturuj", "Tworzy lub rozpoczyna fakturę."), ("Usuń", "Usuwa protokół po potwierdzeniu.")]},
    "oferty": {"permissions": [("access_offer_list", "Wyświetla listę ofert"), ("access_offer_add", "Tworzy ofertę"), ("access_offer_detail", "Otwiera szczegóły"), ("access_offer_update / delete", "Edytuje i usuwa ofertę"), ("access_offer_variant_create / update", "Zarządza wariantami")], "buttons": [("Nowa oferta", "Tworzy ofertę."), ("Dodaj wariant", "Dodaje wariant kosztowy."), ("Wybierz", "Oznacza wariant jako wybrany."), ("Przekaż do realizacji", "Tworzy pracę z oferty."), ("Edytuj / Usuń", "Modyfikuje lub usuwa ofertę.")]},
    "prace": {"permissions": [("access_workorder_list", "Wyświetla listę prac"), ("access_workorder_add", "Tworzy pracę"), ("access_workorder_detail", "Otwiera szczegóły"), ("access_work_update / delete", "Edytuje i usuwa pracę"), ("access_work_schedule_update", "Ustala termin"), ("access_work_assign_workers", "Wyznacza pracowników"), ("access_work_status_update", "Zmienia status")], "buttons": [("Nowa praca", "Tworzy pracę."), ("Ustal termin", "Planuje start i koniec."), ("Wyznacz pracowników", "Przypisuje osoby."), ("Zamówiono sprzęt", "Oznacza zamówienie sprzętu."), ("Status", "Zmienia etap realizacji."), ("Zakończ", "Kończy pracę i uruchamia formularz protokołu.")]},
    "obsluga": {"permissions": [("access_service_contract_list", "Wyświetla umowy"), ("access_service_contract_add", "Tworzy umowę"), ("access_service_contract_detail", "Otwiera szczegóły"), ("access_service_contract_update / delete", "Edytuje i usuwa umowę"), ("access_service_contract_asset_add / update / delete", "Zarządza urządzeniami"), ("access_service_contract_parameter_add / update / delete", "Zarządza parametrami")], "buttons": [("Nowa umowa", "Tworzy umowę obsługi."), ("Dodaj element", "Dodaje urządzenie do umowy."), ("Dodaj parametr", "Dodaje parametr techniczny."), ("Edytuj", "Zmienia dane umowy lub elementu."), ("Usuń", "Usuwa wybrany rekord po potwierdzeniu.")]},
    "gwarancje": {"permissions": [("access_warranty_claim_list", "Wyświetla zgłoszenia"), ("access_warranty_claim_add", "Dodaje zgłoszenie"), ("access_warranty_claim_detail", "Otwiera szczegóły"), ("access_warranty_claim_update / delete", "Edytuje i usuwa zgłoszenie")], "buttons": [("Dodaj zgłoszenie", "Otwiera formularz gwarancyjny."), ("Edytuj", "Zmienia dane usterki."), ("Dodaj zdjęcia", "Dołącza zdjęcia do zgłoszenia."), ("Zmień status", "Przesuwa zgłoszenie w procesie."), ("Usuń", "Usuwa zgłoszenie po potwierdzeniu.")]},
    "zadania": {"permissions": [("access_task_list", "Wyświetla zadania"), ("access_task_add", "Tworzy zadanie"), ("access_task_detail", "Otwiera szczegóły"), ("access_task_update / delete", "Edytuje i usuwa zadanie"), ("access_task_complete", "Oznacza wykonanie")], "buttons": [("Dodaj", "Tworzy zadanie."), ("Wykonano", "Oznacza zadanie jako zakończone."), ("Edytuj", "Zmienia tytuł, opis i termin."), ("Usuń", "Usuwa zadanie.")]},
    "pojazdy": {"permissions": [("access_vehicle_list", "Wyświetla pojazdy"), ("access_vehicle_create", "Dodaje pojazd"), ("access_vehicle_detail", "Otwiera szczegóły"), ("access_vehicle_update / delete", "Edytuje i usuwa pojazd"), ("access_vehicle_event_create / update / delete", "Zarządza zdarzeniami")], "buttons": [("Dodaj pojazd", "Tworzy kartę pojazdu."), ("Dodaj zdarzenie", "Dodaje naprawę, OC, przegląd lub inne zdarzenie."), ("Edytuj", "Zmienia dane pojazdu."), ("Usuń", "Usuwa pojazd po potwierdzeniu.")]},
    "sprzet": {"permissions": [("access_tool_list", "Wyświetla sprzęt"), ("access_tool_create", "Dodaje sprzęt"), ("access_tool_detail", "Otwiera szczegóły"), ("access_tool_update / delete", "Edytuje i usuwa sprzęt"), ("access_tool_event_create", "Dodaje zdarzenie")], "buttons": [("Dodaj sprzęt", "Tworzy kartę sprzętu."), ("Dodaj zdarzenie", "Zapisuje zdarzenie sprzętu."), ("Edytuj", "Zmienia dane sprzętu."), ("Usuń", "Usuwa sprzęt.")]},
    "urzadzenia": {"permissions": [("access_product_list", "Wyświetla urządzenia"), ("access_product_create", "Dodaje urządzenie"), ("access_product_detail", "Otwiera szczegóły"), ("access_product_update / delete", "Edytuje i usuwa urządzenie")], "buttons": [("Dodaj urządzenie", "Tworzy urządzenie w katalogu."), ("Edytuj", "Zmienia dane techniczne."), ("Usuń", "Usuwa urządzenie."), ("Wybierz", "Wstawia urządzenie do formularza serwisu/protokołu.")]},
    "magazyn": {"permissions": [("access_stock_list", "Wyświetla stany"), ("access_stock_create", "Dodaje magazyn"), ("access_stock_detail", "Otwiera magazyn"), ("access_stock_update / delete", "Edytuje i usuwa magazyn"), ("access_stock_movement_add", "Dodaje ruch")], "buttons": [("Dodaj magazyn", "Tworzy magazyn."), ("Dodaj ruch", "Rejestruje przyjęcie, wydanie lub korektę."), ("Szczegóły", "Pokazuje stan i historię ruchów."), ("Usuń", "Usuwa magazyn po potwierdzeniu.")]},
    "rcp": {"permissions": [("access_time_entry_list", "Wyświetla wpisy"), ("access_time_entry_create", "Dodaje czas pracy"), ("access_time_entry_update", "Edytuje wpis"), ("access_time_entry_request_list", "Wyświetla wnioski"), ("access_time_entry_request_approve", "Akceptuje korekty")], "buttons": [("Uzupełnij godziny", "Dodaje wpis czasu pracy."), ("Prośba o edycję", "Wysyła wniosek o korektę."), ("Zatwierdź", "Akceptuje wpis lub korektę."), ("Raport PDF", "Generuje raport godzin.")]},
    "kalendarz": {"permissions": [("access_user_calendar", "Wyświetla kalendarz"), ("access_user_calendar_events", "Pobiera wydarzenia"), ("calendar_personal_event_add", "Dodaje własne wydarzenie"), ("calendar_personal_event_delete", "Usuwa własne wydarzenie")], "buttons": [("Dzień / Tydzień / Miesiąc", "Zmienia widok kalendarza."), ("Dzisiaj", "Wraca do bieżącej daty."), ("Dodaj wydarzenie", "Tworzy własny wpis."), ("Usuń", "Usuwa własne wydarzenie.")]},
    "urlopy": {"permissions": [("access_urlop_add", "Składa wniosek"), ("access_leave_list", "Wyświetla własne urlopy"), ("access_hr_leave_list", "Zarządza wnioskami pracowników"), ("access_leave_approve", "Akceptuje lub odrzuca"), ("access_leave_cancel", "Anuluje zatwierdzony urlop"), ("access_leave_allowance_list", "Zarządza limitami")], "buttons": [("Nowy urlop", "Składa wniosek urlopowy."), ("Zatwierdź / Odrzuć", "Podejmuje decyzję o wniosku."), ("Anuluj urlop", "Anuluje zatwierdzony wniosek i zwraca dni."), ("PDF", "Generuje dokument wniosku.")]},
    "pracownicy": {"permissions": [("access_employee_list", "Wyświetla pracowników"), ("access_employee_add / edit / delete", "Zarządza kontami"), ("access_employee_permission_list / edit", "Nadaje uprawnienia"), ("access_employee_group_create / edit / delete", "Zarządza grupami"), ("access_employee_ownership_transfer", "Przekazuje własność")], "buttons": [("Dodaj pracownika", "Tworzy konto."), ("Role i uprawnienia", "Otwiera konfigurację dostępu."), ("Grupy", "Tworzy grupę uprawnień."), ("Przekaż własność", "Rozpoczyna transfer z potwierdzeniem e-mail.")]},
    "ustawienia-firmy": {"permissions": [("access_company_settings", "Otwiera ustawienia firmy"), ("access_change_package", "Zmienia pakiet"), ("access_cancel_subscription", "Anuluje subskrypcję")], "buttons": [("Zapisz ustawienia", "Zapisuje dane firmy."), ("Logo", "Zmienia logo w pakiecie Pro."), ("Zmień pakiet", "Otwiera wybór pakietu."), ("Anuluj subskrypcję", "Kończy subskrypcję po okresie rozliczeniowym.")]},
    "dokumenty": {"permissions": [("access_documents_list", "Wyświetla dokumenty"), ("access_documents_create", "Dodaje plik"), ("access_documents_update / delete", "Edytuje i usuwa plik"), ("access_document_folder_create", "Tworzy folder")], "buttons": [("Dodaj dokument", "Wgrywa plik."), ("Nowy folder", "Tworzy folder porządkujący."), ("Otwórz", "Pobiera lub podgląda plik."), ("Usuń", "Usuwa dokument.")]},
    "faktury": {"permissions": [("access_invoice_list", "Wyświetla faktury"), ("access_invoice_create", "Tworzy fakturę"), ("access_invoice_detail", "Otwiera szczegóły"), ("access_invoice_update / delete", "Edytuje i usuwa fakturę")], "buttons": [("Nowa faktura", "Tworzy dokument sprzedaży."), ("Dodaj pozycję", "Dodaje pozycję faktury."), ("Zapisz", "Zapisuje dokument."), ("PDF", "Generuje dokument faktury.")]},
    "wsparcie-techniczne": {"permissions": [("access_support_list", "Wyświetla zgłoszenia wsparcia"), ("access_support_create", "Tworzy zgłoszenie"), ("access_support_detail", "Otwiera szczegóły zgłoszenia"), ("access_support_update", "Zmienia opis zgłoszenia"), ("access_support_reply", "Dodaje odpowiedź"), ("access_support_status_update", "Zmienia status zgłoszenia")], "buttons": [("Nowe zgłoszenie", "Otwiera formularz kontaktu ze wsparciem."), ("Odpowiedz", "Dodaje wiadomość do historii."), ("Zmień status", "Przesuwa zgłoszenie w procesie obsługi.")]},
}

MODULE_PURPOSES = {
    "klienci": "Moduł Klienci jest centralną kartoteką kontrahentów firmy. Łączy dane identyfikacyjne i kontaktowe z adresami, lokalizacjami, osobami kontaktowymi oraz całą historią współpracy. Dzięki temu użytkownik może rozpocząć obsługę klienta w jednym miejscu i przejść bezpośrednio do jego serwisów, prac, ofert, protokołów lub faktur.",
    "serwisy": "Moduł Serwisy prowadzi cały proces od przyjęcia zgłoszenia, przez zaplanowanie terminu i przypisanie pracowników, aż do wykonania usługi i utworzenia protokołu. Pozwala rozdzielić zwykły serwis od Obsługi oraz kontrolować rozliczenie godzinowe albo rozliczenie od roboty.",
    "protokoly": "Moduł Protokoły formalizuje wykonanie pracy lub serwisu. Zbiera dane klienta, zakres wykonania, urządzenia, czas, materiały i podpisy, a następnie tworzy dokument PDF, który może być podstawą do fakturowania i zamknięcia realizacji.",
    "oferty": "Moduł Oferty pozwala przygotować klientowi propozycję realizacji przed rozpoczęciem pracy. Użytkownik może porównać warianty, policzyć koszty i zysk, dołączyć pliki, wybrać najlepszy wariant oraz przekazać go bez ponownego przepisywania danych do realizacji.",
    "prace": "Moduł Prace służy do wykonania konkretnego zlecenia. Porządkuje zakres pracy, terminy, osoby, sprzęt, status i koszty, dzięki czemu kierownik widzi postęp, a pracownik wie, co i kiedy ma zrealizować.",
    "obsluga": "Moduł Obsługa obsługuje długoterminową współpracę z klientem, w której urządzenia są serwisowane według umowy. Pozwala utrzymać listę urządzeń, parametrów, elementów umowy i historii działań, zamiast tworzyć te informacje od nowa przy każdej wizycie.",
    "gwarancje": "Moduł Gwarancje organizuje zgłoszenia usterek kierowane do hurtowni lub producentów. Zapewnia komplet informacji potrzebnych do obsługi reklamacji — urządzenie, klienta, miejsce, opis, zdjęcia, status i historię kontaktu.",
    "zadania": "Moduł Zadania zamienia ustalenia i obowiązki w kontrolowane elementy pracy. Pozwala przypisać zadanie konkretnej osobie, całej roli albo firmie, nadać termin i jednoznacznie oznaczyć wykonanie, dzięki czemu nic nie pozostaje bez właściciela.",
    "pojazdy": "Moduł Pojazdy jest ewidencją floty i terminów, które mogą zatrzymać realizację — OC oraz przeglądów. Historia zdarzeń pozwala odtworzyć naprawy, szkody, koszty i inne informacje dotyczące konkretnego pojazdu.",
    "sprzet": "Moduł Sprzęt pokazuje, jakie wyposażenie posiada firma, gdzie jest używane i jaki jest jego stan. Rejestr zdarzeń i załączników ułatwia kontrolę przeglądów, napraw, kosztów oraz odpowiedzialności za sprzęt.",
    "urzadzenia": "Moduł Urządzenia tworzy wspólny katalog urządzeń technicznych używanych w obsłudze klientów. Jedno urządzenie może być wykorzystywane w serwisie, gwarancji, protokole lub umowie, co ogranicza pomyłki i przyspiesza wyszukiwanie.",
    "magazyn": "Moduł Magazyn pokazuje rzeczywisty stan materiałów i sprzętu na podstawie zapisanych ruchów. Rozdziela magazyny, przyjęcia, wydania i korekty, aby można było kontrolować dostępność oraz ustalić, skąd wynika każda zmiana ilości.",
    "rcp": "Moduł RCP rejestruje czas pracy potrzebny do rozliczeń, planowania i raportowania. Łączy wpisy godzinowe z pracownikami, pilnuje domyślnego zakresu dnia pracy i obsługuje formalny proces korekt oraz zatwierdzania.",
    "kalendarz": "Moduł Kalendarz łączy informacje planistyczne z wielu modułów w jednym widoku. Użytkownik może zobaczyć swoje serwisy, prace, urlopy i własne wydarzenia, aby łatwiej zaplanować dzień bez przełączania się między listami.",
    "urlopy": "Moduł Urlopy prowadzi pełny, kontrolowany proces nieobecności: od złożenia wniosku, przez decyzję przełożonego, po pokazanie urlopu w kalendarzu i rozliczenie limitu dni. Chroni też przed wpisaniem czasu pracy w zatwierdzonym dniu wolnym.",
    "pracownicy": "Moduł Pracownicy zarządza cyklem życia kont użytkowników firmy oraz ich dostępem do danych. Obejmuje role, grupy, uprawnienia, bezpieczeństwo logowania, umowy, szkolenia i operacje właścicielskie.",
    "ustawienia-firmy": "Moduł Ustawienia firmy jest miejscem konfiguracji wartości wspólnych dla całej organizacji. Zmiany wykonane tutaj wpływają na dokumenty, numerację, formularze RCP, serwisy, powiadomienia, branding i egzekwowanie pakietu.",
    "dokumenty": "Moduł Dokumenty zapewnia uporządkowane repozytorium plików firmy. Łączy foldery i załączniki z rekordami biznesowymi, zapisuje rozmiary danych i pomaga kontrolować wykorzystanie limitu pamięci pakietu.",
    "faktury": "Moduł Faktury zamyka proces sprzedażowy po wykonaniu pracy lub serwisu. Przenosi dane finansowe do dokumentu, pilnuje pozycji i numeracji oraz pozwala przechowywać wynik rozliczenia w historii firmy.",
    "wsparcie-techniczne": "Moduł Wsparcie techniczne zapewnia użytkownikom jedno miejsce do zgłaszania problemów, pytań i sugestii dotyczących systemu. Porządkuje komunikację z zespołem wsparcia, pozwala śledzić status sprawy, przekazywać dodatkowe informacje i zachować historię rozwiązania.",
}
